if(!localStorage.getItem('loadedchase')){
    localStorage.setItem('chase1', ('$' + (Math.floor((Math.random() * 700) + 5025)).toLocaleString()));
    localStorage.setItem('chase2', ('$' + (Math.floor((Math.random() * 700) + 5725)).toLocaleString()));
    localStorage.setItem('chase3', ('$' + (Math.floor((Math.random() * 700) + 6425)).toLocaleString()));
    localStorage.setItem('chase4', ('$' + (Math.floor((Math.random() * 700) + 7125)).toLocaleString()));
    localStorage.setItem('chase5', ('$' + (Math.floor((Math.random() * 700) + 7825)).toLocaleString()));
    localStorage.setItem('chase6', ('$' + (Math.floor((Math.random() * 700) + 8525)).toLocaleString()));
    localStorage.setItem('chase7', ('$' + (Math.floor((Math.random() * 700) + 9225)).toLocaleString()));
    localStorage.setItem('chase8', ('$' + (Math.floor((Math.random() * 700) + 9925)).toLocaleString()));
    localStorage.setItem('chase9', ('$' + (Math.floor((Math.random() * 700) + 10625)).toLocaleString()));
    localStorage.setItem('chase10', ('$' + (Math.floor((Math.random() * 700) + 11325)).toLocaleString()));
    localStorage.setItem('chase11', ('$' + (Math.floor((Math.random() * 700) + 12025)).toLocaleString()));
    localStorage.setItem('chase12', ('$' + (Math.floor((Math.random() * 700) + 12725)).toLocaleString()));
    localStorage.setItem('chase13', ('$' + (Math.floor((Math.random() * 700) + 13425)).toLocaleString()));
    localStorage.setItem('chase14', ('$' + (Math.floor((Math.random() * 700) + 14125)).toLocaleString()));
    localStorage.setItem('chase15', ('$' + (Math.floor((Math.random() * 700) + 14825)).toLocaleString()));
    localStorage.setItem('chase16', ('$' + (Math.floor((Math.random() * 700) + 15525)).toLocaleString()));
    localStorage.setItem('chase17', ('$' + (Math.floor((Math.random() * 700) + 16225)).toLocaleString()));
    localStorage.setItem('chase18', ('$' + (Math.floor((Math.random() * 700) + 16925)).toLocaleString()));
    localStorage.setItem('chase19', ('$' + (Math.floor((Math.random() * 700) + 17625)).toLocaleString()));
    localStorage.setItem('chase20', ('$' + (Math.floor((Math.random() * 700) + 18325)).toLocaleString()));
    localStorage.setItem('chase21', ('$' + (Math.floor((Math.random() * 700) + 19025)).toLocaleString()));
    localStorage.setItem('chase22', ('$' + (Math.floor((Math.random() * 700) + 19725)).toLocaleString()));
    localStorage.setItem('chase23', ('$' + (Math.floor((Math.random() * 700) + 20425)).toLocaleString()));
    localStorage.setItem('chase24', ('$' + (Math.floor((Math.random() * 700) + 21125)).toLocaleString()));
    localStorage.setItem('chase25', ('$' + (Math.floor((Math.random() * 700) + 22825)).toLocaleString()));
    localStorage.setItem('chase26', ('$' + (Math.floor((Math.random() * 700) + 22525)).toLocaleString()));
    localStorage.setItem('chase27', ('$' + (Math.floor((Math.random() * 700) + 23225)).toLocaleString()));
    localStorage.setItem('chase28', ('$' + (Math.floor((Math.random() * 700) + 23925)).toLocaleString()));
    localStorage.setItem('chase29', ('$' + (Math.floor((Math.random() * 700) + 24625)).toLocaleString()));
    localStorage.setItem('chase30', ('$' + (Math.floor((Math.random() * 700) + 25325)).toLocaleString()));
    localStorage.setItem('chase31', ('$' + (Math.floor((Math.random() * 700) + 26025)).toLocaleString()));
    localStorage.setItem('chase32', ('$' + (Math.floor((Math.random() * 700) + 26725)).toLocaleString()));
    localStorage.setItem('chase33', ('$' + (Math.floor((Math.random() * 700) + 27425)).toLocaleString()));
    localStorage.setItem('chase34', ('$' + (Math.floor((Math.random() * 700) + 28125)).toLocaleString()));
    localStorage.setItem('chase35', ('$' + (Math.floor((Math.random() * 700) + 28825)).toLocaleString()));
    localStorage.setItem('chase36', ('$' + (Math.floor((Math.random() * 700) + 29525)).toLocaleString()));
    localStorage.setItem('chase37', ('$' + (Math.floor((Math.random() * 700) + 30225)).toLocaleString()));
    localStorage.setItem('chase38', ('$' + (Math.floor((Math.random() * 700) + 30925)).toLocaleString()));
    localStorage.setItem('chase39', ('$' + (Math.floor((Math.random() * 700) + 31625)).toLocaleString()));
    localStorage.setItem('chase40', ('$' + (Math.floor((Math.random() * 700) + 32325)).toLocaleString()));
    localStorage.setItem('chase41', ('$' + (Math.floor((Math.random() * 700) + 33025)).toLocaleString()));
    localStorage.setItem('chase42', ('$' + (Math.floor((Math.random() * 700) + 33725)).toLocaleString()));
    localStorage.setItem('chase43', ('$' + (Math.floor((Math.random() * 700) + 34425)).toLocaleString()));
    localStorage.setItem('chase44', ('$' + (Math.floor((Math.random() * 700) + 35125)).toLocaleString()));
    localStorage.setItem('chase45', ('$' + (Math.floor((Math.random() * 700) + 35825)).toLocaleString()));
    localStorage.setItem('chase46', ('$' + (Math.floor((Math.random() * 700) + 36525)).toLocaleString()));
    localStorage.setItem('chase47', ('$' + (Math.floor((Math.random() * 700) + 37225)).toLocaleString()));
    localStorage.setItem('chase48', ('$' + (Math.floor((Math.random() * 700) + 37925)).toLocaleString()));
    localStorage.setItem('chase49', ('$' + (Math.floor((Math.random() * 700) + 38625)).toLocaleString()));
    localStorage.setItem('chase50', ('$' + (Math.floor((Math.random() * 700) + 39325)).toLocaleString()));
    localStorage.setItem('chase51', ('$' + (Math.floor((Math.random() * 700) + 40025)).toLocaleString()));
    localStorage.setItem('chase52', ('$' + (Math.floor((Math.random() * 700) + 40725)).toLocaleString()));
    localStorage.setItem('chase53', ('$' + (Math.floor((Math.random() * 700) + 41425)).toLocaleString()));
    localStorage.setItem('chase54', ('$' + (Math.floor((Math.random() * 700) + 42125)).toLocaleString()));
    localStorage.setItem('chase55', ('$' + (Math.floor((Math.random() * 700) + 42825)).toLocaleString()));
    localStorage.setItem('chase56', ('$' + (Math.floor((Math.random() * 700) + 43525)).toLocaleString()));
    localStorage.setItem('chase57', ('$' + (Math.floor((Math.random() * 700) + 44225)).toLocaleString()));
    localStorage.setItem('chase58', ('$' + (Math.floor((Math.random() * 700) + 44925)).toLocaleString()));



    document.getElementById("chase1").innerHTML = localStorage.getItem('chase1');
    document.getElementById("chase2").innerHTML = localStorage.getItem('chase2');
    document.getElementById("chase3").innerHTML = localStorage.getItem('chase3');
    document.getElementById("chase4").innerHTML = localStorage.getItem('chase4');
    document.getElementById("chase5").innerHTML = localStorage.getItem('chase5');
    document.getElementById("chase6").innerHTML = localStorage.getItem('chase6');
    document.getElementById("chase7").innerHTML = localStorage.getItem('chase7');
    document.getElementById("chase8").innerHTML = localStorage.getItem('chase8');
    document.getElementById("chase9").innerHTML = localStorage.getItem('chase9');
    document.getElementById("chase10").innerHTML = localStorage.getItem('chase10');

    document.getElementById("chase11").innerHTML = localStorage.getItem('chase11');
    document.getElementById("chase12").innerHTML = localStorage.getItem('chase12');
    document.getElementById("chase13").innerHTML = localStorage.getItem('chase13');
    document.getElementById("chase14").innerHTML = localStorage.getItem('chase14');
    document.getElementById("chase15").innerHTML = localStorage.getItem('chase15');
    document.getElementById("chase16").innerHTML = localStorage.getItem('chase16');
    document.getElementById("chase17").innerHTML = localStorage.getItem('chase17');
    document.getElementById("chase18").innerHTML = localStorage.getItem('chase18');
    document.getElementById("chase19").innerHTML = localStorage.getItem('chase19');
    document.getElementById("chase20").innerHTML = localStorage.getItem('chase20');
    document.getElementById("chase21").innerHTML = localStorage.getItem('chase21');
    document.getElementById("chase22").innerHTML = localStorage.getItem('chase22');
    document.getElementById("chase23").innerHTML = localStorage.getItem('chase23');
    document.getElementById("chase24").innerHTML = localStorage.getItem('chase24');
    document.getElementById("chase25").innerHTML = localStorage.getItem('chase25');
    document.getElementById("chase26").innerHTML = localStorage.getItem('chase26');
    document.getElementById("chase27").innerHTML = localStorage.getItem('chase27');
    document.getElementById("chase28").innerHTML = localStorage.getItem('chase28');
    document.getElementById("chase29").innerHTML = localStorage.getItem('chase29');
    document.getElementById("chase30").innerHTML = localStorage.getItem('chase30');
    document.getElementById("chase31").innerHTML = localStorage.getItem('chase31');
    document.getElementById("chase32").innerHTML = localStorage.getItem('chase32');
    document.getElementById("chase33").innerHTML = localStorage.getItem('chase33');
    document.getElementById("chase34").innerHTML = localStorage.getItem('chase34');
    document.getElementById("chase35").innerHTML = localStorage.getItem('chase35');
    document.getElementById("chase36").innerHTML = localStorage.getItem('chase36');
    document.getElementById("chase37").innerHTML = localStorage.getItem('chase37');
    document.getElementById("chase38").innerHTML = localStorage.getItem('chase38');
    document.getElementById("chase39").innerHTML = localStorage.getItem('chase39');
    document.getElementById("chase40").innerHTML = localStorage.getItem('chase40');
    document.getElementById("chase41").innerHTML = localStorage.getItem('chase41');
    document.getElementById("chase42").innerHTML = localStorage.getItem('chase42');
    document.getElementById("chase43").innerHTML = localStorage.getItem('chase43');
    document.getElementById("chase44").innerHTML = localStorage.getItem('chase44');
    document.getElementById("chase45").innerHTML = localStorage.getItem('chase45');
    document.getElementById("chase46").innerHTML = localStorage.getItem('chase46');
    document.getElementById("chase47").innerHTML = localStorage.getItem('chase47');
    document.getElementById("chase48").innerHTML = localStorage.getItem('chase48');
    document.getElementById("chase49").innerHTML = localStorage.getItem('chase49');
    document.getElementById("chase50").innerHTML = localStorage.getItem('chase50');
    document.getElementById("chase51").innerHTML = localStorage.getItem('chase51');
    document.getElementById("chase52").innerHTML = localStorage.getItem('chase52');
    document.getElementById("chase53").innerHTML = localStorage.getItem('chase53');
    document.getElementById("chase54").innerHTML = localStorage.getItem('chase54');
    document.getElementById("chase55").innerHTML = localStorage.getItem('chase55');
    document.getElementById("chase56").innerHTML = localStorage.getItem('chase56');
    document.getElementById("chase57").innerHTML = localStorage.getItem('chase57');
    document.getElementById("chase58").innerHTML = localStorage.getItem('chase58');



    document.getElementById("chase01").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('chase1').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("chase02").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('chase2').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("chase03").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('chase3').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("chase04").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('chase4').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("chase05").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('chase5').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("chase06").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('chase6').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("chase07").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('chase7').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("chase08").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('chase8').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("chase09").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('chase9').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("chase010").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('chase10').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();

    document.getElementById("chase011").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('chase11').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("chase012").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('chase12').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("chase013").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('chase13').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("chase014").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('chase14').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("chase015").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('chase15').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("chase016").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('chase16').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("chase017").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('chase17').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("chase018").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('chase18').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("chase019").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('chase19').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("chase020").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('chase20').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("chase021").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('chase21').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("chase022").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('chase22').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("chase023").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('chase23').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("chase024").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('chase24').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("chase025").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('chase25').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("chase026").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('chase26').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("chase027").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('chase27').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("chase028").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('chase28').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("chase029").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('chase29').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("chase030").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('chase30').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("chase031").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('chase31').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("chase032").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('chase32').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("chase033").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('chase33').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("chase034").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('chase34').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("chase035").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('chase35').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("chase036").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('chase36').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("chase037").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('chase37').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("chase038").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('chase38').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("chase039").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('chase39').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("chase040").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('chase40').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("chase041").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('chase41').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("chase042").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('chase42').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("chase043").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('chase43').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("chase044").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('chase44').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("chase045").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('chase45').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("chase046").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('chase46').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("chase047").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('chase47').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("chase048").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('chase48').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("chase049").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('chase49').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("chase050").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('chase50').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("chase051").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('chase51').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("chase052").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('chase52').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("chase053").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('chase53').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("chase054").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('chase54').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("chase055").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('chase55').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("chase056").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('chase56').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("chase057").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('chase57').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("chase058").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('chase58').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();

} else{
    document.getElementById("chase1").innerHTML = localStorage.getItem('chase1');
    document.getElementById("chase2").innerHTML = localStorage.getItem('chase2');
    document.getElementById("chase3").innerHTML = localStorage.getItem('chase3');
    document.getElementById("chase4").innerHTML = localStorage.getItem('chase4');
    document.getElementById("chase5").innerHTML = localStorage.getItem('chase5');
    document.getElementById("chase6").innerHTML = localStorage.getItem('chase6');
    document.getElementById("chase7").innerHTML = localStorage.getItem('chase7');
    document.getElementById("chase8").innerHTML = localStorage.getItem('chase8');
    document.getElementById("chase9").innerHTML = localStorage.getItem('chase9');
    document.getElementById("chase10").innerHTML = localStorage.getItem('chase10');

    document.getElementById("chase11").innerHTML = localStorage.getItem('chase11');
    document.getElementById("chase12").innerHTML = localStorage.getItem('chase12');
    document.getElementById("chase13").innerHTML = localStorage.getItem('chase13');
    document.getElementById("chase14").innerHTML = localStorage.getItem('chase14');
    document.getElementById("chase15").innerHTML = localStorage.getItem('chase15');
    document.getElementById("chase16").innerHTML = localStorage.getItem('chase16');
    document.getElementById("chase17").innerHTML = localStorage.getItem('chase17');
    document.getElementById("chase18").innerHTML = localStorage.getItem('chase18');
    document.getElementById("chase19").innerHTML = localStorage.getItem('chase19');
    document.getElementById("chase20").innerHTML = localStorage.getItem('chase20');
    document.getElementById("chase21").innerHTML = localStorage.getItem('chase21');
    document.getElementById("chase22").innerHTML = localStorage.getItem('chase22');
    document.getElementById("chase23").innerHTML = localStorage.getItem('chase23');
    document.getElementById("chase24").innerHTML = localStorage.getItem('chase24');
    document.getElementById("chase25").innerHTML = localStorage.getItem('chase25');
    document.getElementById("chase26").innerHTML = localStorage.getItem('chase26');
    document.getElementById("chase27").innerHTML = localStorage.getItem('chase27');
    document.getElementById("chase28").innerHTML = localStorage.getItem('chase28');
    document.getElementById("chase29").innerHTML = localStorage.getItem('chase29');
    document.getElementById("chase30").innerHTML = localStorage.getItem('chase30');
    document.getElementById("chase31").innerHTML = localStorage.getItem('chase31');
    document.getElementById("chase32").innerHTML = localStorage.getItem('chase32');
    document.getElementById("chase33").innerHTML = localStorage.getItem('chase33');
    document.getElementById("chase34").innerHTML = localStorage.getItem('chase34');
    document.getElementById("chase35").innerHTML = localStorage.getItem('chase35');
    document.getElementById("chase36").innerHTML = localStorage.getItem('chase36');
    document.getElementById("chase37").innerHTML = localStorage.getItem('chase37');
    document.getElementById("chase38").innerHTML = localStorage.getItem('chase38');
    document.getElementById("chase39").innerHTML = localStorage.getItem('chase39');
    document.getElementById("chase40").innerHTML = localStorage.getItem('chase40');
    document.getElementById("chase41").innerHTML = localStorage.getItem('chase41');
    document.getElementById("chase42").innerHTML = localStorage.getItem('chase42');
    document.getElementById("chase43").innerHTML = localStorage.getItem('chase43');
    document.getElementById("chase44").innerHTML = localStorage.getItem('chase44');
    document.getElementById("chase45").innerHTML = localStorage.getItem('chase45');
    document.getElementById("chase46").innerHTML = localStorage.getItem('chase46');
    document.getElementById("chase47").innerHTML = localStorage.getItem('chase47');
    document.getElementById("chase48").innerHTML = localStorage.getItem('chase48');
    document.getElementById("chase49").innerHTML = localStorage.getItem('chase49');
    document.getElementById("chase50").innerHTML = localStorage.getItem('chase50');
    document.getElementById("chase51").innerHTML = localStorage.getItem('chase51');
    document.getElementById("chase52").innerHTML = localStorage.getItem('chase52');
    document.getElementById("chase53").innerHTML = localStorage.getItem('chase53');
    document.getElementById("chase54").innerHTML = localStorage.getItem('chase54');
    document.getElementById("chase55").innerHTML = localStorage.getItem('chase55');
    document.getElementById("chase56").innerHTML = localStorage.getItem('chase56');
    document.getElementById("chase57").innerHTML = localStorage.getItem('chase57');
    document.getElementById("chase58").innerHTML = localStorage.getItem('chase58');



    document.getElementById("chase01").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('chase1').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("chase02").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('chase2').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("chase03").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('chase3').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("chase04").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('chase4').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("chase05").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('chase5').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("chase06").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('chase6').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("chase07").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('chase7').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("chase08").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('chase8').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("chase09").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('chase9').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("chase010").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('chase10').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();

    document.getElementById("chase011").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('chase11').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("chase012").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('chase12').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("chase013").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('chase13').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("chase014").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('chase14').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("chase015").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('chase15').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("chase016").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('chase16').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("chase017").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('chase17').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("chase018").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('chase18').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("chase019").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('chase19').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("chase020").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('chase20').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("chase021").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('chase21').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("chase022").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('chase22').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("chase023").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('chase23').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("chase024").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('chase24').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("chase025").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('chase25').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("chase026").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('chase26').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("chase027").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('chase27').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("chase028").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('chase28').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("chase029").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('chase29').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("chase030").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('chase30').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("chase031").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('chase31').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("chase032").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('chase32').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("chase033").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('chase33').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("chase034").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('chase34').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("chase035").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('chase35').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("chase036").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('chase36').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("chase037").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('chase37').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("chase038").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('chase38').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("chase039").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('chase39').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("chase040").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('chase40').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("chase041").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('chase41').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("chase042").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('chase42').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("chase043").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('chase43').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("chase044").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('chase44').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("chase045").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('chase45').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("chase046").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('chase46').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("chase047").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('chase47').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("chase048").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('chase48').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("chase049").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('chase49').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("chase050").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('chase50').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("chase051").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('chase51').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("chase052").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('chase52').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("chase053").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('chase53').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("chase054").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('chase54').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("chase055").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('chase55').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("chase056").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('chase56').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("chase057").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('chase57').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("chase058").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('chase58').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();

}

localStorage.setItem('loadedchase',true);
