if(!localStorage.getItem('loadedbbt')){
    localStorage.setItem('bbt1', ('$' + (Math.floor((Math.random() * 700) + 10025)).toLocaleString()));
    localStorage.setItem('bbt2', ('$' + (Math.floor((Math.random() * 700) + 10725)).toLocaleString()));
    localStorage.setItem('bbt3', ('$' + (Math.floor((Math.random() * 700) + 11425)).toLocaleString()));
    localStorage.setItem('bbt4', ('$' + (Math.floor((Math.random() * 700) + 12125)).toLocaleString()));
    localStorage.setItem('bbt5', ('$' + (Math.floor((Math.random() * 700) + 12825)).toLocaleString()));
    localStorage.setItem('bbt6', ('$' + (Math.floor((Math.random() * 700) + 13525)).toLocaleString()));
    localStorage.setItem('bbt7', ('$' + (Math.floor((Math.random() * 700) + 14225)).toLocaleString()));
    localStorage.setItem('bbt8', ('$' + (Math.floor((Math.random() * 700) + 14925)).toLocaleString()));
    localStorage.setItem('bbt9', ('$' + (Math.floor((Math.random() * 700) + 15625)).toLocaleString()));
    localStorage.setItem('bbt10', ('$' + (Math.floor((Math.random() * 700) + 16325)).toLocaleString()));
    localStorage.setItem('bbt11', ('$' + (Math.floor((Math.random() * 700) + 17025)).toLocaleString()));
    localStorage.setItem('bbt12', ('$' + (Math.floor((Math.random() * 700) + 18725)).toLocaleString()));
    localStorage.setItem('bbt13', ('$' + (Math.floor((Math.random() * 700) + 18425)).toLocaleString()));
    localStorage.setItem('bbt14', ('$' + (Math.floor((Math.random() * 700) + 19125)).toLocaleString()));
    localStorage.setItem('bbt15', ('$' + (Math.floor((Math.random() * 700) + 19825)).toLocaleString()));
    localStorage.setItem('bbt16', ('$' + (Math.floor((Math.random() * 700) + 20525)).toLocaleString()));
    localStorage.setItem('bbt17', ('$' + (Math.floor((Math.random() * 700) + 21225)).toLocaleString()));
    localStorage.setItem('bbt18', ('$' + (Math.floor((Math.random() * 700) + 21925)).toLocaleString()));
    localStorage.setItem('bbt19', ('$' + (Math.floor((Math.random() * 700) + 22625)).toLocaleString()));
    localStorage.setItem('bbt20', ('$' + (Math.floor((Math.random() * 700) + 23325)).toLocaleString()));
    localStorage.setItem('bbt21', ('$' + (Math.floor((Math.random() * 700) + 24025)).toLocaleString()));
    localStorage.setItem('bbt22', ('$' + (Math.floor((Math.random() * 700) + 24725)).toLocaleString()));
    localStorage.setItem('bbt23', ('$' + (Math.floor((Math.random() * 700) + 25425)).toLocaleString()));
    localStorage.setItem('bbt24', ('$' + (Math.floor((Math.random() * 700) + 26125)).toLocaleString()));
    localStorage.setItem('bbt25', ('$' + (Math.floor((Math.random() * 700) + 27825)).toLocaleString()));
    localStorage.setItem('bbt26', ('$' + (Math.floor((Math.random() * 700) + 27525)).toLocaleString()));
    localStorage.setItem('bbt27', ('$' + (Math.floor((Math.random() * 700) + 28225)).toLocaleString()));
    localStorage.setItem('bbt28', ('$' + (Math.floor((Math.random() * 700) + 28925)).toLocaleString()));
    localStorage.setItem('bbt29', ('$' + (Math.floor((Math.random() * 700) + 29625)).toLocaleString()));
    localStorage.setItem('bbt30', ('$' + (Math.floor((Math.random() * 700) + 30325)).toLocaleString()));
    localStorage.setItem('bbt31', ('$' + (Math.floor((Math.random() * 700) + 31025)).toLocaleString()));
    localStorage.setItem('bbt32', ('$' + (Math.floor((Math.random() * 700) + 31725)).toLocaleString()));
    localStorage.setItem('bbt33', ('$' + (Math.floor((Math.random() * 700) + 32425)).toLocaleString()));
    localStorage.setItem('bbt34', ('$' + (Math.floor((Math.random() * 700) + 33125)).toLocaleString()));
    localStorage.setItem('bbt35', ('$' + (Math.floor((Math.random() * 700) + 33825)).toLocaleString()));
    localStorage.setItem('bbt36', ('$' + (Math.floor((Math.random() * 700) + 34525)).toLocaleString()));
    localStorage.setItem('bbt37', ('$' + (Math.floor((Math.random() * 700) + 35225)).toLocaleString()));
    localStorage.setItem('bbt38', ('$' + (Math.floor((Math.random() * 700) + 35925)).toLocaleString()));
    localStorage.setItem('bbt39', ('$' + (Math.floor((Math.random() * 700) + 36625)).toLocaleString()));
    localStorage.setItem('bbt40', ('$' + (Math.floor((Math.random() * 700) + 37325)).toLocaleString()));
    localStorage.setItem('bbt41', ('$' + (Math.floor((Math.random() * 700) + 38025)).toLocaleString()));
    localStorage.setItem('bbt42', ('$' + (Math.floor((Math.random() * 700) + 38725)).toLocaleString()));
    localStorage.setItem('bbt43', ('$' + (Math.floor((Math.random() * 700) + 39425)).toLocaleString()));
    localStorage.setItem('bbt44', ('$' + (Math.floor((Math.random() * 700) + 40125)).toLocaleString()));
    localStorage.setItem('bbt45', ('$' + (Math.floor((Math.random() * 700) + 40825)).toLocaleString()));
    localStorage.setItem('bbt46', ('$' + (Math.floor((Math.random() * 700) + 41525)).toLocaleString()));
    localStorage.setItem('bbt47', ('$' + (Math.floor((Math.random() * 700) + 42225)).toLocaleString()));
    localStorage.setItem('bbt48', ('$' + (Math.floor((Math.random() * 700) + 42925)).toLocaleString()));
    localStorage.setItem('bbt49', ('$' + (Math.floor((Math.random() * 700) + 43625)).toLocaleString()));
    localStorage.setItem('bbt50', ('$' + (Math.floor((Math.random() * 700) + 44325)).toLocaleString()));
    localStorage.setItem('bbt51', ('$' + (Math.floor((Math.random() * 700) + 45025)).toLocaleString()));
    localStorage.setItem('bbt52', ('$' + (Math.floor((Math.random() * 700) + 45725)).toLocaleString()));
    localStorage.setItem('bbt53', ('$' + (Math.floor((Math.random() * 700) + 46425)).toLocaleString()));
    localStorage.setItem('bbt54', ('$' + (Math.floor((Math.random() * 700) + 47125)).toLocaleString()));
    localStorage.setItem('bbt55', ('$' + (Math.floor((Math.random() * 700) + 47825)).toLocaleString()));
    localStorage.setItem('bbt56', ('$' + (Math.floor((Math.random() * 700) + 48525)).toLocaleString()));
    localStorage.setItem('bbt57', ('$' + (Math.floor((Math.random() * 700) + 49225)).toLocaleString()));
    localStorage.setItem('bbt58', ('$' + (Math.floor((Math.random() * 700) + 49925)).toLocaleString()));
    localStorage.setItem('bbt59', ('$' + (Math.floor((Math.random() * 700) + 50625)).toLocaleString()));



    document.getElementById("bbt1").innerHTML = localStorage.getItem('bbt1');
    document.getElementById("bbt2").innerHTML = localStorage.getItem('bbt2');
    document.getElementById("bbt3").innerHTML = localStorage.getItem('bbt3');
    document.getElementById("bbt4").innerHTML = localStorage.getItem('bbt4');
    document.getElementById("bbt5").innerHTML = localStorage.getItem('bbt5');
    document.getElementById("bbt6").innerHTML = localStorage.getItem('bbt6');
    document.getElementById("bbt7").innerHTML = localStorage.getItem('bbt7');
    document.getElementById("bbt8").innerHTML = localStorage.getItem('bbt8');
    document.getElementById("bbt9").innerHTML = localStorage.getItem('bbt9');
    document.getElementById("bbt10").innerHTML = localStorage.getItem('bbt10');

    document.getElementById("bbt11").innerHTML = localStorage.getItem('bbt11');
    document.getElementById("bbt12").innerHTML = localStorage.getItem('bbt12');
    document.getElementById("bbt13").innerHTML = localStorage.getItem('bbt13');
    document.getElementById("bbt14").innerHTML = localStorage.getItem('bbt14');
    document.getElementById("bbt15").innerHTML = localStorage.getItem('bbt15');
    document.getElementById("bbt16").innerHTML = localStorage.getItem('bbt16');
    document.getElementById("bbt17").innerHTML = localStorage.getItem('bbt17');
    document.getElementById("bbt18").innerHTML = localStorage.getItem('bbt18');
    document.getElementById("bbt19").innerHTML = localStorage.getItem('bbt19');
    document.getElementById("bbt20").innerHTML = localStorage.getItem('bbt20');
    document.getElementById("bbt21").innerHTML = localStorage.getItem('bbt21');
    document.getElementById("bbt22").innerHTML = localStorage.getItem('bbt22');
    document.getElementById("bbt23").innerHTML = localStorage.getItem('bbt23');
    document.getElementById("bbt24").innerHTML = localStorage.getItem('bbt24');
    document.getElementById("bbt25").innerHTML = localStorage.getItem('bbt25');
    document.getElementById("bbt26").innerHTML = localStorage.getItem('bbt26');
    document.getElementById("bbt27").innerHTML = localStorage.getItem('bbt27');
    document.getElementById("bbt28").innerHTML = localStorage.getItem('bbt28');
    document.getElementById("bbt29").innerHTML = localStorage.getItem('bbt29');
    document.getElementById("bbt30").innerHTML = localStorage.getItem('bbt30');
    document.getElementById("bbt31").innerHTML = localStorage.getItem('bbt31');
    document.getElementById("bbt32").innerHTML = localStorage.getItem('bbt32');
    document.getElementById("bbt33").innerHTML = localStorage.getItem('bbt33');
    document.getElementById("bbt34").innerHTML = localStorage.getItem('bbt34');
    document.getElementById("bbt35").innerHTML = localStorage.getItem('bbt35');
    document.getElementById("bbt36").innerHTML = localStorage.getItem('bbt36');
    document.getElementById("bbt37").innerHTML = localStorage.getItem('bbt37');
    document.getElementById("bbt38").innerHTML = localStorage.getItem('bbt38');
    document.getElementById("bbt39").innerHTML = localStorage.getItem('bbt39');
    document.getElementById("bbt40").innerHTML = localStorage.getItem('bbt40');
    document.getElementById("bbt41").innerHTML = localStorage.getItem('bbt41');
    document.getElementById("bbt42").innerHTML = localStorage.getItem('bbt42');
    document.getElementById("bbt43").innerHTML = localStorage.getItem('bbt43');
    document.getElementById("bbt44").innerHTML = localStorage.getItem('bbt44');
    document.getElementById("bbt45").innerHTML = localStorage.getItem('bbt45');
    document.getElementById("bbt46").innerHTML = localStorage.getItem('bbt46');
    document.getElementById("bbt47").innerHTML = localStorage.getItem('bbt47');
    document.getElementById("bbt48").innerHTML = localStorage.getItem('bbt48');
    document.getElementById("bbt49").innerHTML = localStorage.getItem('bbt49');
    document.getElementById("bbt50").innerHTML = localStorage.getItem('bbt50');
    document.getElementById("bbt51").innerHTML = localStorage.getItem('bbt51');
    document.getElementById("bbt52").innerHTML = localStorage.getItem('bbt52');
    document.getElementById("bbt53").innerHTML = localStorage.getItem('bbt53');
    document.getElementById("bbt54").innerHTML = localStorage.getItem('bbt54');
    document.getElementById("bbt55").innerHTML = localStorage.getItem('bbt55');
    document.getElementById("bbt56").innerHTML = localStorage.getItem('bbt56');
    document.getElementById("bbt57").innerHTML = localStorage.getItem('bbt57');
    document.getElementById("bbt58").innerHTML = localStorage.getItem('bbt58');
    document.getElementById("bbt59").innerHTML = localStorage.getItem('bbt59');



    document.getElementById("bbt01").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('bbt1').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("bbt02").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('bbt2').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("bbt03").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('bbt3').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("bbt04").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('bbt4').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("bbt05").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('bbt5').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("bbt06").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('bbt6').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("bbt07").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('bbt7').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("bbt08").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('bbt8').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("bbt09").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('bbt9').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("bbt010").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('bbt10').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();

    document.getElementById("bbt011").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('bbt11').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("bbt012").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('bbt12').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("bbt013").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('bbt13').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("bbt014").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('bbt14').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("bbt015").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('bbt15').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("bbt016").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('bbt16').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("bbt017").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('bbt17').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("bbt018").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('bbt18').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("bbt019").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('bbt19').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("bbt020").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('bbt20').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("bbt021").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('bbt21').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("bbt022").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('bbt22').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("bbt023").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('bbt23').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("bbt024").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('bbt24').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("bbt025").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('bbt25').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("bbt026").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('bbt26').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("bbt027").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('bbt27').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("bbt028").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('bbt28').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("bbt029").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('bbt29').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("bbt030").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('bbt30').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("bbt031").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('bbt31').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("bbt032").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('bbt32').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("bbt033").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('bbt33').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("bbt034").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('bbt34').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("bbt035").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('bbt35').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("bbt036").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('bbt36').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("bbt037").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('bbt37').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("bbt038").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('bbt38').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("bbt039").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('bbt39').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("bbt040").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('bbt40').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("bbt041").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('bbt41').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("bbt042").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('bbt42').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("bbt043").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('bbt43').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("bbt044").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('bbt44').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("bbt045").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('bbt45').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("bbt046").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('bbt46').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("bbt047").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('bbt47').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("bbt048").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('bbt48').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("bbt049").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('bbt49').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("bbt050").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('bbt50').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("bbt051").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('bbt51').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("bbt052").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('bbt52').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("bbt053").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('bbt53').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("bbt054").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('bbt54').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("bbt055").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('bbt55').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("bbt056").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('bbt56').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("bbt057").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('bbt57').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("bbt058").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('bbt58').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("bbt059").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('bbt59').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();

} else{
    document.getElementById("bbt1").innerHTML = localStorage.getItem('bbt1');
    document.getElementById("bbt2").innerHTML = localStorage.getItem('bbt2');
    document.getElementById("bbt3").innerHTML = localStorage.getItem('bbt3');
    document.getElementById("bbt4").innerHTML = localStorage.getItem('bbt4');
    document.getElementById("bbt5").innerHTML = localStorage.getItem('bbt5');
    document.getElementById("bbt6").innerHTML = localStorage.getItem('bbt6');
    document.getElementById("bbt7").innerHTML = localStorage.getItem('bbt7');
    document.getElementById("bbt8").innerHTML = localStorage.getItem('bbt8');
    document.getElementById("bbt9").innerHTML = localStorage.getItem('bbt9');
    document.getElementById("bbt10").innerHTML = localStorage.getItem('bbt10');

    document.getElementById("bbt11").innerHTML = localStorage.getItem('bbt11');
    document.getElementById("bbt12").innerHTML = localStorage.getItem('bbt12');
    document.getElementById("bbt13").innerHTML = localStorage.getItem('bbt13');
    document.getElementById("bbt14").innerHTML = localStorage.getItem('bbt14');
    document.getElementById("bbt15").innerHTML = localStorage.getItem('bbt15');
    document.getElementById("bbt16").innerHTML = localStorage.getItem('bbt16');
    document.getElementById("bbt17").innerHTML = localStorage.getItem('bbt17');
    document.getElementById("bbt18").innerHTML = localStorage.getItem('bbt18');
    document.getElementById("bbt19").innerHTML = localStorage.getItem('bbt19');
    document.getElementById("bbt20").innerHTML = localStorage.getItem('bbt20');
    document.getElementById("bbt21").innerHTML = localStorage.getItem('bbt21');
    document.getElementById("bbt22").innerHTML = localStorage.getItem('bbt22');
    document.getElementById("bbt23").innerHTML = localStorage.getItem('bbt23');
    document.getElementById("bbt24").innerHTML = localStorage.getItem('bbt24');
    document.getElementById("bbt25").innerHTML = localStorage.getItem('bbt25');
    document.getElementById("bbt26").innerHTML = localStorage.getItem('bbt26');
    document.getElementById("bbt27").innerHTML = localStorage.getItem('bbt27');
    document.getElementById("bbt28").innerHTML = localStorage.getItem('bbt28');
    document.getElementById("bbt29").innerHTML = localStorage.getItem('bbt29');
    document.getElementById("bbt30").innerHTML = localStorage.getItem('bbt30');
    document.getElementById("bbt31").innerHTML = localStorage.getItem('bbt31');
    document.getElementById("bbt32").innerHTML = localStorage.getItem('bbt32');
    document.getElementById("bbt33").innerHTML = localStorage.getItem('bbt33');
    document.getElementById("bbt34").innerHTML = localStorage.getItem('bbt34');
    document.getElementById("bbt35").innerHTML = localStorage.getItem('bbt35');
    document.getElementById("bbt36").innerHTML = localStorage.getItem('bbt36');
    document.getElementById("bbt37").innerHTML = localStorage.getItem('bbt37');
    document.getElementById("bbt38").innerHTML = localStorage.getItem('bbt38');
    document.getElementById("bbt39").innerHTML = localStorage.getItem('bbt39');
    document.getElementById("bbt40").innerHTML = localStorage.getItem('bbt40');
    document.getElementById("bbt41").innerHTML = localStorage.getItem('bbt41');
    document.getElementById("bbt42").innerHTML = localStorage.getItem('bbt42');
    document.getElementById("bbt43").innerHTML = localStorage.getItem('bbt43');
    document.getElementById("bbt44").innerHTML = localStorage.getItem('bbt44');
    document.getElementById("bbt45").innerHTML = localStorage.getItem('bbt45');
    document.getElementById("bbt46").innerHTML = localStorage.getItem('bbt46');
    document.getElementById("bbt47").innerHTML = localStorage.getItem('bbt47');
    document.getElementById("bbt48").innerHTML = localStorage.getItem('bbt48');
    document.getElementById("bbt49").innerHTML = localStorage.getItem('bbt49');
    document.getElementById("bbt50").innerHTML = localStorage.getItem('bbt50');
    document.getElementById("bbt51").innerHTML = localStorage.getItem('bbt51');
    document.getElementById("bbt52").innerHTML = localStorage.getItem('bbt52');
    document.getElementById("bbt53").innerHTML = localStorage.getItem('bbt53');
    document.getElementById("bbt54").innerHTML = localStorage.getItem('bbt54');
    document.getElementById("bbt55").innerHTML = localStorage.getItem('bbt55');
    document.getElementById("bbt56").innerHTML = localStorage.getItem('bbt56');
    document.getElementById("bbt57").innerHTML = localStorage.getItem('bbt57');
    document.getElementById("bbt58").innerHTML = localStorage.getItem('bbt58');
    document.getElementById("bbt59").innerHTML = localStorage.getItem('bbt59');



    document.getElementById("bbt01").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('bbt1').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("bbt02").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('bbt2').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("bbt03").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('bbt3').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("bbt04").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('bbt4').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("bbt05").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('bbt5').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("bbt06").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('bbt6').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("bbt07").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('bbt7').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("bbt08").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('bbt8').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("bbt09").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('bbt9').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("bbt010").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('bbt10').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();

    document.getElementById("bbt011").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('bbt11').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("bbt012").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('bbt12').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("bbt013").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('bbt13').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("bbt014").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('bbt14').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("bbt015").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('bbt15').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("bbt016").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('bbt16').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("bbt017").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('bbt17').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("bbt018").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('bbt18').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("bbt019").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('bbt19').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("bbt020").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('bbt20').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("bbt021").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('bbt21').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("bbt022").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('bbt22').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("bbt023").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('bbt23').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("bbt024").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('bbt24').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("bbt025").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('bbt25').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("bbt026").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('bbt26').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("bbt027").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('bbt27').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("bbt028").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('bbt28').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("bbt029").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('bbt29').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("bbt030").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('bbt30').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("bbt031").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('bbt31').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("bbt032").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('bbt32').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("bbt033").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('bbt33').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("bbt034").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('bbt34').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("bbt035").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('bbt35').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("bbt036").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('bbt36').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("bbt037").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('bbt37').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("bbt038").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('bbt38').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("bbt039").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('bbt39').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("bbt040").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('bbt40').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("bbt041").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('bbt41').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("bbt042").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('bbt42').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("bbt043").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('bbt43').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("bbt044").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('bbt44').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("bbt045").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('bbt45').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("bbt046").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('bbt46').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("bbt047").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('bbt47').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("bbt048").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('bbt48').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("bbt049").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('bbt49').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("bbt050").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('bbt50').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("bbt051").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('bbt51').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("bbt052").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('bbt52').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("bbt053").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('bbt53').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("bbt054").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('bbt54').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("bbt055").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('bbt55').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("bbt056").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('bbt56').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("bbt057").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('bbt57').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("bbt058").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('bbt58').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("bbt059").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('bbt59').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();

}

localStorage.setItem('loadedbbt',true);
