if(!localStorage.getItem('loadedciti')){
    localStorage.setItem('citi1', ('$' + (Math.floor((Math.random() * 700) + 10025)).toLocaleString()));
    localStorage.setItem('citi2', ('$' + (Math.floor((Math.random() * 700) + 10725)).toLocaleString()));
    localStorage.setItem('citi3', ('$' + (Math.floor((Math.random() * 700) + 11425)).toLocaleString()));
    localStorage.setItem('citi4', ('$' + (Math.floor((Math.random() * 700) + 12125)).toLocaleString()));
    localStorage.setItem('citi5', ('$' + (Math.floor((Math.random() * 700) + 12825)).toLocaleString()));
    localStorage.setItem('citi6', ('$' + (Math.floor((Math.random() * 700) + 13525)).toLocaleString()));
    localStorage.setItem('citi7', ('$' + (Math.floor((Math.random() * 700) + 14225)).toLocaleString()));
    localStorage.setItem('citi8', ('$' + (Math.floor((Math.random() * 700) + 14925)).toLocaleString()));
    localStorage.setItem('citi9', ('$' + (Math.floor((Math.random() * 700) + 15625)).toLocaleString()));
    localStorage.setItem('citi10', ('$' + (Math.floor((Math.random() * 700) + 16325)).toLocaleString()));
    localStorage.setItem('citi11', ('$' + (Math.floor((Math.random() * 700) + 17025)).toLocaleString()));
    localStorage.setItem('citi12', ('$' + (Math.floor((Math.random() * 700) + 17725)).toLocaleString()));
    localStorage.setItem('citi13', ('$' + (Math.floor((Math.random() * 700) + 18425)).toLocaleString()));
    localStorage.setItem('citi14', ('$' + (Math.floor((Math.random() * 700) + 19125)).toLocaleString()));
    localStorage.setItem('citi15', ('$' + (Math.floor((Math.random() * 700) + 19825)).toLocaleString()));
    localStorage.setItem('citi16', ('$' + (Math.floor((Math.random() * 700) + 20525)).toLocaleString()));
    localStorage.setItem('citi17', ('$' + (Math.floor((Math.random() * 700) + 21225)).toLocaleString()));
    localStorage.setItem('citi18', ('$' + (Math.floor((Math.random() * 700) + 21925)).toLocaleString()));
    localStorage.setItem('citi19', ('$' + (Math.floor((Math.random() * 700) + 22625)).toLocaleString()));
    localStorage.setItem('citi20', ('$' + (Math.floor((Math.random() * 700) + 23325)).toLocaleString()));
    localStorage.setItem('citi21', ('$' + (Math.floor((Math.random() * 700) + 24025)).toLocaleString()));
    localStorage.setItem('citi22', ('$' + (Math.floor((Math.random() * 700) + 24725)).toLocaleString()));
    localStorage.setItem('citi23', ('$' + (Math.floor((Math.random() * 700) + 25425)).toLocaleString()));
    localStorage.setItem('citi24', ('$' + (Math.floor((Math.random() * 700) + 26125)).toLocaleString()));
    localStorage.setItem('citi25', ('$' + (Math.floor((Math.random() * 700) + 27825)).toLocaleString()));
    localStorage.setItem('citi26', ('$' + (Math.floor((Math.random() * 700) + 27525)).toLocaleString()));
    localStorage.setItem('citi27', ('$' + (Math.floor((Math.random() * 700) + 28225)).toLocaleString()));
    localStorage.setItem('citi28', ('$' + (Math.floor((Math.random() * 700) + 28925)).toLocaleString()));
    localStorage.setItem('citi29', ('$' + (Math.floor((Math.random() * 700) + 29625)).toLocaleString()));
    localStorage.setItem('citi30', ('$' + (Math.floor((Math.random() * 700) + 30325)).toLocaleString()));
    localStorage.setItem('citi31', ('$' + (Math.floor((Math.random() * 700) + 31025)).toLocaleString()));
    localStorage.setItem('citi32', ('$' + (Math.floor((Math.random() * 700) + 31725)).toLocaleString()));
    localStorage.setItem('citi33', ('$' + (Math.floor((Math.random() * 700) + 32425)).toLocaleString()));
    localStorage.setItem('citi34', ('$' + (Math.floor((Math.random() * 700) + 33125)).toLocaleString()));
    localStorage.setItem('citi35', ('$' + (Math.floor((Math.random() * 700) + 33825)).toLocaleString()));
    localStorage.setItem('citi36', ('$' + (Math.floor((Math.random() * 700) + 34525)).toLocaleString()));
    localStorage.setItem('citi37', ('$' + (Math.floor((Math.random() * 700) + 35225)).toLocaleString()));
    localStorage.setItem('citi38', ('$' + (Math.floor((Math.random() * 700) + 35925)).toLocaleString()));
    localStorage.setItem('citi39', ('$' + (Math.floor((Math.random() * 700) + 36625)).toLocaleString()));
    localStorage.setItem('citi40', ('$' + (Math.floor((Math.random() * 700) + 37325)).toLocaleString()));
    localStorage.setItem('citi41', ('$' + (Math.floor((Math.random() * 700) + 38025)).toLocaleString()));
    localStorage.setItem('citi42', ('$' + (Math.floor((Math.random() * 700) + 38725)).toLocaleString()));
    localStorage.setItem('citi43', ('$' + (Math.floor((Math.random() * 700) + 39425)).toLocaleString()));
    localStorage.setItem('citi44', ('$' + (Math.floor((Math.random() * 700) + 40125)).toLocaleString()));
    localStorage.setItem('citi45', ('$' + (Math.floor((Math.random() * 700) + 40825)).toLocaleString()));
    localStorage.setItem('citi46', ('$' + (Math.floor((Math.random() * 700) + 41525)).toLocaleString()));
    localStorage.setItem('citi47', ('$' + (Math.floor((Math.random() * 700) + 42225)).toLocaleString()));
    localStorage.setItem('citi48', ('$' + (Math.floor((Math.random() * 700) + 42925)).toLocaleString()));
    localStorage.setItem('citi49', ('$' + (Math.floor((Math.random() * 700) + 43625)).toLocaleString()));
    localStorage.setItem('citi50', ('$' + (Math.floor((Math.random() * 700) + 44325)).toLocaleString()));
    localStorage.setItem('citi51', ('$' + (Math.floor((Math.random() * 700) + 45025)).toLocaleString()));
    localStorage.setItem('citi52', ('$' + (Math.floor((Math.random() * 700) + 45725)).toLocaleString()));
    localStorage.setItem('citi53', ('$' + (Math.floor((Math.random() * 700) + 46425)).toLocaleString()));
    localStorage.setItem('citi54', ('$' + (Math.floor((Math.random() * 700) + 47125)).toLocaleString()));
    localStorage.setItem('citi55', ('$' + (Math.floor((Math.random() * 700) + 47825)).toLocaleString()));
    localStorage.setItem('citi56', ('$' + (Math.floor((Math.random() * 700) + 48525)).toLocaleString()));
    localStorage.setItem('citi57', ('$' + (Math.floor((Math.random() * 700) + 49225)).toLocaleString()));



    document.getElementById("citi1").innerHTML = localStorage.getItem('citi1');
    document.getElementById("citi2").innerHTML = localStorage.getItem('citi2');
    document.getElementById("citi3").innerHTML = localStorage.getItem('citi3');
    document.getElementById("citi4").innerHTML = localStorage.getItem('citi4');
    document.getElementById("citi5").innerHTML = localStorage.getItem('citi5');
    document.getElementById("citi6").innerHTML = localStorage.getItem('citi6');
    document.getElementById("citi7").innerHTML = localStorage.getItem('citi7');
    document.getElementById("citi8").innerHTML = localStorage.getItem('citi8');
    document.getElementById("citi9").innerHTML = localStorage.getItem('citi9');
    document.getElementById("citi10").innerHTML = localStorage.getItem('citi10');

    document.getElementById("citi11").innerHTML = localStorage.getItem('citi11');
    document.getElementById("citi12").innerHTML = localStorage.getItem('citi12');
    document.getElementById("citi13").innerHTML = localStorage.getItem('citi13');
    document.getElementById("citi14").innerHTML = localStorage.getItem('citi14');
    document.getElementById("citi15").innerHTML = localStorage.getItem('citi15');
    document.getElementById("citi16").innerHTML = localStorage.getItem('citi16');
    document.getElementById("citi17").innerHTML = localStorage.getItem('citi17');
    document.getElementById("citi18").innerHTML = localStorage.getItem('citi18');
    document.getElementById("citi19").innerHTML = localStorage.getItem('citi19');
    document.getElementById("citi20").innerHTML = localStorage.getItem('citi20');
    document.getElementById("citi21").innerHTML = localStorage.getItem('citi21');
    document.getElementById("citi22").innerHTML = localStorage.getItem('citi22');
    document.getElementById("citi23").innerHTML = localStorage.getItem('citi23');
    document.getElementById("citi24").innerHTML = localStorage.getItem('citi24');
    document.getElementById("citi25").innerHTML = localStorage.getItem('citi25');
    document.getElementById("citi26").innerHTML = localStorage.getItem('citi26');
    document.getElementById("citi27").innerHTML = localStorage.getItem('citi27');
    document.getElementById("citi28").innerHTML = localStorage.getItem('citi28');
    document.getElementById("citi29").innerHTML = localStorage.getItem('citi29');
    document.getElementById("citi30").innerHTML = localStorage.getItem('citi30');
    document.getElementById("citi31").innerHTML = localStorage.getItem('citi31');
    document.getElementById("citi32").innerHTML = localStorage.getItem('citi32');
    document.getElementById("citi33").innerHTML = localStorage.getItem('citi33');
    document.getElementById("citi34").innerHTML = localStorage.getItem('citi34');
    document.getElementById("citi35").innerHTML = localStorage.getItem('citi35');
    document.getElementById("citi36").innerHTML = localStorage.getItem('citi36');
    document.getElementById("citi37").innerHTML = localStorage.getItem('citi37');
    document.getElementById("citi38").innerHTML = localStorage.getItem('citi38');
    document.getElementById("citi39").innerHTML = localStorage.getItem('citi39');
    document.getElementById("citi40").innerHTML = localStorage.getItem('citi40');
    document.getElementById("citi41").innerHTML = localStorage.getItem('citi41');
    document.getElementById("citi42").innerHTML = localStorage.getItem('citi42');
    document.getElementById("citi43").innerHTML = localStorage.getItem('citi43');
    document.getElementById("citi44").innerHTML = localStorage.getItem('citi44');
    document.getElementById("citi45").innerHTML = localStorage.getItem('citi45');
    document.getElementById("citi46").innerHTML = localStorage.getItem('citi46');
    document.getElementById("citi47").innerHTML = localStorage.getItem('citi47');
    document.getElementById("citi48").innerHTML = localStorage.getItem('citi48');
    document.getElementById("citi49").innerHTML = localStorage.getItem('citi49');
    document.getElementById("citi50").innerHTML = localStorage.getItem('citi50');
    document.getElementById("citi51").innerHTML = localStorage.getItem('citi51');
    document.getElementById("citi52").innerHTML = localStorage.getItem('citi52');
    document.getElementById("citi53").innerHTML = localStorage.getItem('citi53');
    document.getElementById("citi54").innerHTML = localStorage.getItem('citi54');
    document.getElementById("citi55").innerHTML = localStorage.getItem('citi55');
    document.getElementById("citi56").innerHTML = localStorage.getItem('citi56');
    document.getElementById("citi57").innerHTML = localStorage.getItem('citi57');



    document.getElementById("citi01").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('citi1').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("citi02").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('citi2').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("citi03").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('citi3').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("citi04").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('citi4').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("citi05").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('citi5').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("citi06").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('citi6').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("citi07").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('citi7').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("citi08").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('citi8').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("citi09").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('citi9').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("citi010").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('citi10').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();

    document.getElementById("citi011").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('citi11').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("citi012").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('citi12').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("citi013").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('citi13').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("citi014").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('citi14').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("citi015").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('citi15').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("citi016").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('citi16').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("citi017").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('citi17').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("citi018").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('citi18').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("citi019").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('citi19').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("citi020").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('citi20').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("citi021").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('citi21').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("citi022").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('citi22').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("citi023").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('citi23').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("citi024").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('citi24').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("citi025").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('citi25').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("citi026").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('citi26').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("citi027").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('citi27').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("citi028").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('citi28').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("citi029").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('citi29').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("citi030").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('citi30').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("citi031").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('citi31').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("citi032").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('citi32').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("citi033").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('citi33').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("citi034").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('citi34').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("citi035").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('citi35').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("citi036").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('citi36').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("citi037").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('citi37').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("citi038").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('citi38').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("citi039").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('citi39').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("citi040").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('citi40').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("citi041").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('citi41').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("citi042").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('citi42').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("citi043").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('citi43').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("citi044").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('citi44').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("citi045").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('citi45').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("citi046").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('citi46').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("citi047").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('citi47').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("citi048").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('citi48').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("citi049").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('citi49').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("citi050").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('citi50').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("citi051").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('citi51').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("citi052").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('citi52').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("citi053").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('citi53').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("citi054").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('citi54').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("citi055").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('citi55').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("citi056").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('citi56').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("citi057").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('citi57').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();

} else{
    document.getElementById("citi1").innerHTML = localStorage.getItem('citi1');
    document.getElementById("citi2").innerHTML = localStorage.getItem('citi2');
    document.getElementById("citi3").innerHTML = localStorage.getItem('citi3');
    document.getElementById("citi4").innerHTML = localStorage.getItem('citi4');
    document.getElementById("citi5").innerHTML = localStorage.getItem('citi5');
    document.getElementById("citi6").innerHTML = localStorage.getItem('citi6');
    document.getElementById("citi7").innerHTML = localStorage.getItem('citi7');
    document.getElementById("citi8").innerHTML = localStorage.getItem('citi8');
    document.getElementById("citi9").innerHTML = localStorage.getItem('citi9');
    document.getElementById("citi10").innerHTML = localStorage.getItem('citi10');

    document.getElementById("citi11").innerHTML = localStorage.getItem('citi11');
    document.getElementById("citi12").innerHTML = localStorage.getItem('citi12');
    document.getElementById("citi13").innerHTML = localStorage.getItem('citi13');
    document.getElementById("citi14").innerHTML = localStorage.getItem('citi14');
    document.getElementById("citi15").innerHTML = localStorage.getItem('citi15');
    document.getElementById("citi16").innerHTML = localStorage.getItem('citi16');
    document.getElementById("citi17").innerHTML = localStorage.getItem('citi17');
    document.getElementById("citi18").innerHTML = localStorage.getItem('citi18');
    document.getElementById("citi19").innerHTML = localStorage.getItem('citi19');
    document.getElementById("citi20").innerHTML = localStorage.getItem('citi20');
    document.getElementById("citi21").innerHTML = localStorage.getItem('citi21');
    document.getElementById("citi22").innerHTML = localStorage.getItem('citi22');
    document.getElementById("citi23").innerHTML = localStorage.getItem('citi23');
    document.getElementById("citi24").innerHTML = localStorage.getItem('citi24');
    document.getElementById("citi25").innerHTML = localStorage.getItem('citi25');
    document.getElementById("citi26").innerHTML = localStorage.getItem('citi26');
    document.getElementById("citi27").innerHTML = localStorage.getItem('citi27');
    document.getElementById("citi28").innerHTML = localStorage.getItem('citi28');
    document.getElementById("citi29").innerHTML = localStorage.getItem('citi29');
    document.getElementById("citi30").innerHTML = localStorage.getItem('citi30');
    document.getElementById("citi31").innerHTML = localStorage.getItem('citi31');
    document.getElementById("citi32").innerHTML = localStorage.getItem('citi32');
    document.getElementById("citi33").innerHTML = localStorage.getItem('citi33');
    document.getElementById("citi34").innerHTML = localStorage.getItem('citi34');
    document.getElementById("citi35").innerHTML = localStorage.getItem('citi35');
    document.getElementById("citi36").innerHTML = localStorage.getItem('citi36');
    document.getElementById("citi37").innerHTML = localStorage.getItem('citi37');
    document.getElementById("citi38").innerHTML = localStorage.getItem('citi38');
    document.getElementById("citi39").innerHTML = localStorage.getItem('citi39');
    document.getElementById("citi40").innerHTML = localStorage.getItem('citi40');
    document.getElementById("citi41").innerHTML = localStorage.getItem('citi41');
    document.getElementById("citi42").innerHTML = localStorage.getItem('citi42');
    document.getElementById("citi43").innerHTML = localStorage.getItem('citi43');
    document.getElementById("citi44").innerHTML = localStorage.getItem('citi44');
    document.getElementById("citi45").innerHTML = localStorage.getItem('citi45');
    document.getElementById("citi46").innerHTML = localStorage.getItem('citi46');
    document.getElementById("citi47").innerHTML = localStorage.getItem('citi47');
    document.getElementById("citi48").innerHTML = localStorage.getItem('citi48');
    document.getElementById("citi49").innerHTML = localStorage.getItem('citi49');
    document.getElementById("citi50").innerHTML = localStorage.getItem('citi50');
    document.getElementById("citi51").innerHTML = localStorage.getItem('citi51');
    document.getElementById("citi52").innerHTML = localStorage.getItem('citi52');
    document.getElementById("citi53").innerHTML = localStorage.getItem('citi53');
    document.getElementById("citi54").innerHTML = localStorage.getItem('citi54');
    document.getElementById("citi55").innerHTML = localStorage.getItem('citi55');
    document.getElementById("citi56").innerHTML = localStorage.getItem('citi56');
    document.getElementById("citi57").innerHTML = localStorage.getItem('citi57');



    document.getElementById("citi01").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('citi1').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("citi02").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('citi2').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("citi03").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('citi3').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("citi04").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('citi4').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("citi05").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('citi5').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("citi06").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('citi6').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("citi07").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('citi7').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("citi08").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('citi8').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("citi09").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('citi9').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("citi010").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('citi10').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();

    document.getElementById("citi011").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('citi11').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("citi012").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('citi12').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("citi013").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('citi13').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("citi014").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('citi14').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("citi015").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('citi15').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("citi016").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('citi16').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("citi017").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('citi17').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("citi018").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('citi18').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("citi019").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('citi19').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("citi020").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('citi20').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("citi021").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('citi21').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("citi022").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('citi22').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("citi023").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('citi23').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("citi024").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('citi24').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("citi025").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('citi25').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("citi026").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('citi26').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("citi027").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('citi27').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("citi028").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('citi28').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("citi029").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('citi29').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("citi030").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('citi30').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("citi031").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('citi31').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("citi032").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('citi32').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("citi033").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('citi33').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("citi034").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('citi34').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("citi035").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('citi35').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("citi036").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('citi36').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("citi037").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('citi37').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("citi038").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('citi38').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("citi039").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('citi39').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("citi040").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('citi40').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("citi041").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('citi41').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("citi042").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('citi42').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("citi043").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('citi43').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("citi044").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('citi44').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("citi045").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('citi45').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("citi046").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('citi46').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("citi047").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('citi47').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("citi048").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('citi48').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("citi049").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('citi49').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("citi050").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('citi50').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("citi051").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('citi51').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("citi052").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('citi52').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("citi053").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('citi53').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("citi054").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('citi54').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("citi055").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('citi55').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("citi056").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('citi56').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("citi057").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('citi57').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();

}

localStorage.setItem('loadedciti',true);
