if(!localStorage.getItem('loadedhunt')){
    localStorage.setItem('hunt1', ('$' + (Math.floor((Math.random() * 700) + 10025)).toLocaleString()));
    localStorage.setItem('hunt2', ('$' + (Math.floor((Math.random() * 700) + 10725)).toLocaleString()));
    localStorage.setItem('hunt3', ('$' + (Math.floor((Math.random() * 700) + 11425)).toLocaleString()));
    localStorage.setItem('hunt4', ('$' + (Math.floor((Math.random() * 700) + 12125)).toLocaleString()));
    localStorage.setItem('hunt5', ('$' + (Math.floor((Math.random() * 700) + 12825)).toLocaleString()));
    localStorage.setItem('hunt6', ('$' + (Math.floor((Math.random() * 700) + 13525)).toLocaleString()));
    localStorage.setItem('hunt7', ('$' + (Math.floor((Math.random() * 700) + 14225)).toLocaleString()));
    localStorage.setItem('hunt8', ('$' + (Math.floor((Math.random() * 700) + 14925)).toLocaleString()));
    localStorage.setItem('hunt9', ('$' + (Math.floor((Math.random() * 700) + 15625)).toLocaleString()));
    localStorage.setItem('hunt10', ('$' + (Math.floor((Math.random() * 700) + 16325)).toLocaleString()));
    localStorage.setItem('hunt11', ('$' + (Math.floor((Math.random() * 700) + 17025)).toLocaleString()));
    localStorage.setItem('hunt12', ('$' + (Math.floor((Math.random() * 700) + 18725)).toLocaleString()));
    localStorage.setItem('hunt13', ('$' + (Math.floor((Math.random() * 700) + 18425)).toLocaleString()));
    localStorage.setItem('hunt14', ('$' + (Math.floor((Math.random() * 700) + 19125)).toLocaleString()));
    localStorage.setItem('hunt15', ('$' + (Math.floor((Math.random() * 700) + 19825)).toLocaleString()));
    localStorage.setItem('hunt16', ('$' + (Math.floor((Math.random() * 700) + 20525)).toLocaleString()));
    localStorage.setItem('hunt17', ('$' + (Math.floor((Math.random() * 700) + 21225)).toLocaleString()));
    localStorage.setItem('hunt18', ('$' + (Math.floor((Math.random() * 700) + 21925)).toLocaleString()));
    localStorage.setItem('hunt19', ('$' + (Math.floor((Math.random() * 700) + 22625)).toLocaleString()));
    localStorage.setItem('hunt20', ('$' + (Math.floor((Math.random() * 700) + 23325)).toLocaleString()));
    localStorage.setItem('hunt21', ('$' + (Math.floor((Math.random() * 700) + 24025)).toLocaleString()));
    localStorage.setItem('hunt22', ('$' + (Math.floor((Math.random() * 700) + 24725)).toLocaleString()));
    localStorage.setItem('hunt23', ('$' + (Math.floor((Math.random() * 700) + 25425)).toLocaleString()));
    localStorage.setItem('hunt24', ('$' + (Math.floor((Math.random() * 700) + 26125)).toLocaleString()));
    localStorage.setItem('hunt25', ('$' + (Math.floor((Math.random() * 700) + 27825)).toLocaleString()));
    localStorage.setItem('hunt26', ('$' + (Math.floor((Math.random() * 700) + 27525)).toLocaleString()));
    localStorage.setItem('hunt27', ('$' + (Math.floor((Math.random() * 700) + 28225)).toLocaleString()));
    localStorage.setItem('hunt28', ('$' + (Math.floor((Math.random() * 700) + 28925)).toLocaleString()));
    localStorage.setItem('hunt29', ('$' + (Math.floor((Math.random() * 700) + 29625)).toLocaleString()));
    localStorage.setItem('hunt30', ('$' + (Math.floor((Math.random() * 700) + 30325)).toLocaleString()));
    localStorage.setItem('hunt31', ('$' + (Math.floor((Math.random() * 700) + 31025)).toLocaleString()));
    localStorage.setItem('hunt32', ('$' + (Math.floor((Math.random() * 700) + 31725)).toLocaleString()));
    localStorage.setItem('hunt33', ('$' + (Math.floor((Math.random() * 700) + 32425)).toLocaleString()));
    localStorage.setItem('hunt34', ('$' + (Math.floor((Math.random() * 700) + 33125)).toLocaleString()));
    localStorage.setItem('hunt35', ('$' + (Math.floor((Math.random() * 700) + 33825)).toLocaleString()));
    localStorage.setItem('hunt36', ('$' + (Math.floor((Math.random() * 700) + 34525)).toLocaleString()));
    localStorage.setItem('hunt37', ('$' + (Math.floor((Math.random() * 700) + 35225)).toLocaleString()));
    localStorage.setItem('hunt38', ('$' + (Math.floor((Math.random() * 700) + 35925)).toLocaleString()));
    localStorage.setItem('hunt39', ('$' + (Math.floor((Math.random() * 700) + 36625)).toLocaleString()));
    localStorage.setItem('hunt40', ('$' + (Math.floor((Math.random() * 700) + 37325)).toLocaleString()));
    localStorage.setItem('hunt41', ('$' + (Math.floor((Math.random() * 700) + 38025)).toLocaleString()));
    localStorage.setItem('hunt42', ('$' + (Math.floor((Math.random() * 700) + 38725)).toLocaleString()));
    localStorage.setItem('hunt43', ('$' + (Math.floor((Math.random() * 700) + 39425)).toLocaleString()));
    localStorage.setItem('hunt44', ('$' + (Math.floor((Math.random() * 700) + 40125)).toLocaleString()));
    localStorage.setItem('hunt45', ('$' + (Math.floor((Math.random() * 700) + 40825)).toLocaleString()));
    localStorage.setItem('hunt46', ('$' + (Math.floor((Math.random() * 700) + 41525)).toLocaleString()));
    localStorage.setItem('hunt47', ('$' + (Math.floor((Math.random() * 700) + 42225)).toLocaleString()));
    localStorage.setItem('hunt48', ('$' + (Math.floor((Math.random() * 700) + 42925)).toLocaleString()));
    localStorage.setItem('hunt49', ('$' + (Math.floor((Math.random() * 700) + 43625)).toLocaleString()));
    localStorage.setItem('hunt50', ('$' + (Math.floor((Math.random() * 700) + 44325)).toLocaleString()));
    localStorage.setItem('hunt51', ('$' + (Math.floor((Math.random() * 700) + 45025)).toLocaleString()));
    localStorage.setItem('hunt52', ('$' + (Math.floor((Math.random() * 700) + 45725)).toLocaleString()));
    localStorage.setItem('hunt53', ('$' + (Math.floor((Math.random() * 700) + 46425)).toLocaleString()));
    localStorage.setItem('hunt54', ('$' + (Math.floor((Math.random() * 700) + 47125)).toLocaleString()));
    localStorage.setItem('hunt55', ('$' + (Math.floor((Math.random() * 700) + 47825)).toLocaleString()));
    localStorage.setItem('hunt56', ('$' + (Math.floor((Math.random() * 700) + 48525)).toLocaleString()));


    document.getElementById("hunt1").innerHTML = localStorage.getItem('hunt1');
    document.getElementById("hunt2").innerHTML = localStorage.getItem('hunt2');
    document.getElementById("hunt3").innerHTML = localStorage.getItem('hunt3');
    document.getElementById("hunt4").innerHTML = localStorage.getItem('hunt4');
    document.getElementById("hunt5").innerHTML = localStorage.getItem('hunt5');
    document.getElementById("hunt6").innerHTML = localStorage.getItem('hunt6');
    document.getElementById("hunt7").innerHTML = localStorage.getItem('hunt7');
    document.getElementById("hunt8").innerHTML = localStorage.getItem('hunt8');
    document.getElementById("hunt9").innerHTML = localStorage.getItem('hunt9');
    document.getElementById("hunt10").innerHTML = localStorage.getItem('hunt10');

    document.getElementById("hunt11").innerHTML = localStorage.getItem('hunt11');
    document.getElementById("hunt12").innerHTML = localStorage.getItem('hunt12');
    document.getElementById("hunt13").innerHTML = localStorage.getItem('hunt13');
    document.getElementById("hunt14").innerHTML = localStorage.getItem('hunt14');
    document.getElementById("hunt15").innerHTML = localStorage.getItem('hunt15');
    document.getElementById("hunt16").innerHTML = localStorage.getItem('hunt16');
    document.getElementById("hunt17").innerHTML = localStorage.getItem('hunt17');
    document.getElementById("hunt18").innerHTML = localStorage.getItem('hunt18');
    document.getElementById("hunt19").innerHTML = localStorage.getItem('hunt19');
    document.getElementById("hunt20").innerHTML = localStorage.getItem('hunt20');
    document.getElementById("hunt21").innerHTML = localStorage.getItem('hunt21');
    document.getElementById("hunt22").innerHTML = localStorage.getItem('hunt22');
    document.getElementById("hunt23").innerHTML = localStorage.getItem('hunt23');
    document.getElementById("hunt24").innerHTML = localStorage.getItem('hunt24');
    document.getElementById("hunt25").innerHTML = localStorage.getItem('hunt25');
    document.getElementById("hunt26").innerHTML = localStorage.getItem('hunt26');
    document.getElementById("hunt27").innerHTML = localStorage.getItem('hunt27');
    document.getElementById("hunt28").innerHTML = localStorage.getItem('hunt28');
    document.getElementById("hunt29").innerHTML = localStorage.getItem('hunt29');
    document.getElementById("hunt30").innerHTML = localStorage.getItem('hunt30');
    document.getElementById("hunt31").innerHTML = localStorage.getItem('hunt31');
    document.getElementById("hunt32").innerHTML = localStorage.getItem('hunt32');
    document.getElementById("hunt33").innerHTML = localStorage.getItem('hunt33');
    document.getElementById("hunt34").innerHTML = localStorage.getItem('hunt34');
    document.getElementById("hunt35").innerHTML = localStorage.getItem('hunt35');
    document.getElementById("hunt36").innerHTML = localStorage.getItem('hunt36');
    document.getElementById("hunt37").innerHTML = localStorage.getItem('hunt37');
    document.getElementById("hunt38").innerHTML = localStorage.getItem('hunt38');
    document.getElementById("hunt39").innerHTML = localStorage.getItem('hunt39');
    document.getElementById("hunt40").innerHTML = localStorage.getItem('hunt40');
    document.getElementById("hunt41").innerHTML = localStorage.getItem('hunt41');
    document.getElementById("hunt42").innerHTML = localStorage.getItem('hunt42');
    document.getElementById("hunt43").innerHTML = localStorage.getItem('hunt43');
    document.getElementById("hunt44").innerHTML = localStorage.getItem('hunt44');
    document.getElementById("hunt45").innerHTML = localStorage.getItem('hunt45');
    document.getElementById("hunt46").innerHTML = localStorage.getItem('hunt46');
    document.getElementById("hunt47").innerHTML = localStorage.getItem('hunt47');
    document.getElementById("hunt48").innerHTML = localStorage.getItem('hunt48');
    document.getElementById("hunt49").innerHTML = localStorage.getItem('hunt49');
    document.getElementById("hunt50").innerHTML = localStorage.getItem('hunt50');
    document.getElementById("hunt51").innerHTML = localStorage.getItem('hunt51');
    document.getElementById("hunt52").innerHTML = localStorage.getItem('hunt52');
    document.getElementById("hunt53").innerHTML = localStorage.getItem('hunt53');
    document.getElementById("hunt54").innerHTML = localStorage.getItem('hunt54');
    document.getElementById("hunt55").innerHTML = localStorage.getItem('hunt55');
    document.getElementById("hunt56").innerHTML = localStorage.getItem('hunt56');



    document.getElementById("hunt01").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('hunt1').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("hunt02").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('hunt2').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("hunt03").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('hunt3').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("hunt04").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('hunt4').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("hunt05").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('hunt5').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("hunt06").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('hunt6').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("hunt07").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('hunt7').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("hunt08").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('hunt8').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("hunt09").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('hunt9').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("hunt010").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('hunt10').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();

    document.getElementById("hunt011").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('hunt11').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("hunt012").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('hunt12').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("hunt013").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('hunt13').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("hunt014").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('hunt14').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("hunt015").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('hunt15').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("hunt016").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('hunt16').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("hunt017").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('hunt17').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("hunt018").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('hunt18').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("hunt019").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('hunt19').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("hunt020").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('hunt20').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("hunt021").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('hunt21').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("hunt022").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('hunt22').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("hunt023").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('hunt23').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("hunt024").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('hunt24').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("hunt025").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('hunt25').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("hunt026").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('hunt26').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("hunt027").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('hunt27').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("hunt028").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('hunt28').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("hunt029").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('hunt29').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("hunt030").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('hunt30').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("hunt031").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('hunt31').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("hunt032").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('hunt32').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("hunt033").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('hunt33').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("hunt034").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('hunt34').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("hunt035").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('hunt35').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("hunt036").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('hunt36').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("hunt037").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('hunt37').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("hunt038").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('hunt38').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("hunt039").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('hunt39').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("hunt040").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('hunt40').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("hunt041").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('hunt41').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("hunt042").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('hunt42').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("hunt043").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('hunt43').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("hunt044").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('hunt44').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("hunt045").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('hunt45').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("hunt046").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('hunt46').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("hunt047").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('hunt47').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("hunt048").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('hunt48').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("hunt049").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('hunt49').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("hunt050").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('hunt50').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("hunt051").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('hunt51').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("hunt052").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('hunt52').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("hunt053").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('hunt53').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("hunt054").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('hunt54').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("hunt055").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('hunt55').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("hunt056").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('hunt56').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();

} else{
    document.getElementById("hunt1").innerHTML = localStorage.getItem('hunt1');
    document.getElementById("hunt2").innerHTML = localStorage.getItem('hunt2');
    document.getElementById("hunt3").innerHTML = localStorage.getItem('hunt3');
    document.getElementById("hunt4").innerHTML = localStorage.getItem('hunt4');
    document.getElementById("hunt5").innerHTML = localStorage.getItem('hunt5');
    document.getElementById("hunt6").innerHTML = localStorage.getItem('hunt6');
    document.getElementById("hunt7").innerHTML = localStorage.getItem('hunt7');
    document.getElementById("hunt8").innerHTML = localStorage.getItem('hunt8');
    document.getElementById("hunt9").innerHTML = localStorage.getItem('hunt9');
    document.getElementById("hunt10").innerHTML = localStorage.getItem('hunt10');

    document.getElementById("hunt11").innerHTML = localStorage.getItem('hunt11');
    document.getElementById("hunt12").innerHTML = localStorage.getItem('hunt12');
    document.getElementById("hunt13").innerHTML = localStorage.getItem('hunt13');
    document.getElementById("hunt14").innerHTML = localStorage.getItem('hunt14');
    document.getElementById("hunt15").innerHTML = localStorage.getItem('hunt15');
    document.getElementById("hunt16").innerHTML = localStorage.getItem('hunt16');
    document.getElementById("hunt17").innerHTML = localStorage.getItem('hunt17');
    document.getElementById("hunt18").innerHTML = localStorage.getItem('hunt18');
    document.getElementById("hunt19").innerHTML = localStorage.getItem('hunt19');
    document.getElementById("hunt20").innerHTML = localStorage.getItem('hunt20');
    document.getElementById("hunt21").innerHTML = localStorage.getItem('hunt21');
    document.getElementById("hunt22").innerHTML = localStorage.getItem('hunt22');
    document.getElementById("hunt23").innerHTML = localStorage.getItem('hunt23');
    document.getElementById("hunt24").innerHTML = localStorage.getItem('hunt24');
    document.getElementById("hunt25").innerHTML = localStorage.getItem('hunt25');
    document.getElementById("hunt26").innerHTML = localStorage.getItem('hunt26');
    document.getElementById("hunt27").innerHTML = localStorage.getItem('hunt27');
    document.getElementById("hunt28").innerHTML = localStorage.getItem('hunt28');
    document.getElementById("hunt29").innerHTML = localStorage.getItem('hunt29');
    document.getElementById("hunt30").innerHTML = localStorage.getItem('hunt30');
    document.getElementById("hunt31").innerHTML = localStorage.getItem('hunt31');
    document.getElementById("hunt32").innerHTML = localStorage.getItem('hunt32');
    document.getElementById("hunt33").innerHTML = localStorage.getItem('hunt33');
    document.getElementById("hunt34").innerHTML = localStorage.getItem('hunt34');
    document.getElementById("hunt35").innerHTML = localStorage.getItem('hunt35');
    document.getElementById("hunt36").innerHTML = localStorage.getItem('hunt36');
    document.getElementById("hunt37").innerHTML = localStorage.getItem('hunt37');
    document.getElementById("hunt38").innerHTML = localStorage.getItem('hunt38');
    document.getElementById("hunt39").innerHTML = localStorage.getItem('hunt39');
    document.getElementById("hunt40").innerHTML = localStorage.getItem('hunt40');
    document.getElementById("hunt41").innerHTML = localStorage.getItem('hunt41');
    document.getElementById("hunt42").innerHTML = localStorage.getItem('hunt42');
    document.getElementById("hunt43").innerHTML = localStorage.getItem('hunt43');
    document.getElementById("hunt44").innerHTML = localStorage.getItem('hunt44');
    document.getElementById("hunt45").innerHTML = localStorage.getItem('hunt45');
    document.getElementById("hunt46").innerHTML = localStorage.getItem('hunt46');
    document.getElementById("hunt47").innerHTML = localStorage.getItem('hunt47');
    document.getElementById("hunt48").innerHTML = localStorage.getItem('hunt48');
    document.getElementById("hunt49").innerHTML = localStorage.getItem('hunt49');
    document.getElementById("hunt50").innerHTML = localStorage.getItem('hunt50');
    document.getElementById("hunt51").innerHTML = localStorage.getItem('hunt51');
    document.getElementById("hunt52").innerHTML = localStorage.getItem('hunt52');
    document.getElementById("hunt53").innerHTML = localStorage.getItem('hunt53');
    document.getElementById("hunt54").innerHTML = localStorage.getItem('hunt54');
    document.getElementById("hunt55").innerHTML = localStorage.getItem('hunt55');
    document.getElementById("hunt56").innerHTML = localStorage.getItem('hunt56');



    document.getElementById("hunt01").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('hunt1').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("hunt02").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('hunt2').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("hunt03").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('hunt3').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("hunt04").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('hunt4').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("hunt05").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('hunt5').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("hunt06").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('hunt6').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("hunt07").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('hunt7').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("hunt08").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('hunt8').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("hunt09").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('hunt9').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("hunt010").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('hunt10').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();

    document.getElementById("hunt011").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('hunt11').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("hunt012").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('hunt12').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("hunt013").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('hunt13').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("hunt014").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('hunt14').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("hunt015").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('hunt15').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("hunt016").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('hunt16').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("hunt017").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('hunt17').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("hunt018").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('hunt18').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("hunt019").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('hunt19').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("hunt020").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('hunt20').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("hunt021").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('hunt21').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("hunt022").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('hunt22').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("hunt023").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('hunt23').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("hunt024").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('hunt24').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("hunt025").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('hunt25').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("hunt026").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('hunt26').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("hunt027").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('hunt27').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("hunt028").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('hunt28').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("hunt029").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('hunt29').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("hunt030").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('hunt30').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("hunt031").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('hunt31').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("hunt032").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('hunt32').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("hunt033").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('hunt33').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("hunt034").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('hunt34').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("hunt035").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('hunt35').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("hunt036").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('hunt36').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("hunt037").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('hunt37').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("hunt038").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('hunt38').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("hunt039").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('hunt39').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("hunt040").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('hunt40').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("hunt041").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('hunt41').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("hunt042").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('hunt42').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("hunt043").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('hunt43').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("hunt044").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('hunt44').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("hunt045").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('hunt45').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("hunt046").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('hunt46').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("hunt047").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('hunt47').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("hunt048").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('hunt48').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("hunt049").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('hunt49').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("hunt050").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('hunt50').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("hunt051").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('hunt51').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("hunt052").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('hunt52').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("hunt053").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('hunt53').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("hunt054").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('hunt54').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("hunt055").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('hunt55').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("hunt056").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('hunt56').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();

}

localStorage.setItem('loadedhunt',true);
