if(!localStorage.getItem('loadedscotia')){
    localStorage.setItem('scotia1', ('$' + (Math.floor((Math.random() * 700) + 5025)).toLocaleString()));
    localStorage.setItem('scotia2', ('$' + (Math.floor((Math.random() * 700) + 5725)).toLocaleString()));
    localStorage.setItem('scotia3', ('$' + (Math.floor((Math.random() * 700) + 6425)).toLocaleString()));
    localStorage.setItem('scotia4', ('$' + (Math.floor((Math.random() * 700) + 7125)).toLocaleString()));
    localStorage.setItem('scotia5', ('$' + (Math.floor((Math.random() * 700) + 7825)).toLocaleString()));
    localStorage.setItem('scotia6', ('$' + (Math.floor((Math.random() * 700) + 8525)).toLocaleString()));
    localStorage.setItem('scotia7', ('$' + (Math.floor((Math.random() * 700) + 9225)).toLocaleString()));
    localStorage.setItem('scotia8', ('$' + (Math.floor((Math.random() * 700) + 9925)).toLocaleString()));
    localStorage.setItem('scotia9', ('$' + (Math.floor((Math.random() * 700) + 10625)).toLocaleString()));
    localStorage.setItem('scotia10', ('$' + (Math.floor((Math.random() * 700) + 11325)).toLocaleString()));
    localStorage.setItem('scotia11', ('$' + (Math.floor((Math.random() * 700) + 12025)).toLocaleString()));
    localStorage.setItem('scotia12', ('$' + (Math.floor((Math.random() * 700) + 13725)).toLocaleString()));
    localStorage.setItem('scotia13', ('$' + (Math.floor((Math.random() * 700) + 13425)).toLocaleString()));
    localStorage.setItem('scotia14', ('$' + (Math.floor((Math.random() * 700) + 14125)).toLocaleString()));
    localStorage.setItem('scotia15', ('$' + (Math.floor((Math.random() * 700) + 14825)).toLocaleString()));
    localStorage.setItem('scotia16', ('$' + (Math.floor((Math.random() * 700) + 15525)).toLocaleString()));
    localStorage.setItem('scotia17', ('$' + (Math.floor((Math.random() * 700) + 16225)).toLocaleString()));
    localStorage.setItem('scotia18', ('$' + (Math.floor((Math.random() * 700) + 16925)).toLocaleString()));
    localStorage.setItem('scotia19', ('$' + (Math.floor((Math.random() * 700) + 17625)).toLocaleString()));
    localStorage.setItem('scotia20', ('$' + (Math.floor((Math.random() * 700) + 18325)).toLocaleString()));
    localStorage.setItem('scotia21', ('$' + (Math.floor((Math.random() * 700) + 19025)).toLocaleString()));
    localStorage.setItem('scotia22', ('$' + (Math.floor((Math.random() * 700) + 19725)).toLocaleString()));
    localStorage.setItem('scotia23', ('$' + (Math.floor((Math.random() * 700) + 20425)).toLocaleString()));
    localStorage.setItem('scotia24', ('$' + (Math.floor((Math.random() * 700) + 21125)).toLocaleString()));
    localStorage.setItem('scotia25', ('$' + (Math.floor((Math.random() * 700) + 22825)).toLocaleString()));
    localStorage.setItem('scotia26', ('$' + (Math.floor((Math.random() * 700) + 22525)).toLocaleString()));
    localStorage.setItem('scotia27', ('$' + (Math.floor((Math.random() * 700) + 23225)).toLocaleString()));
    localStorage.setItem('scotia28', ('$' + (Math.floor((Math.random() * 700) + 23925)).toLocaleString()));
    localStorage.setItem('scotia29', ('$' + (Math.floor((Math.random() * 700) + 24625)).toLocaleString()));
    localStorage.setItem('scotia30', ('$' + (Math.floor((Math.random() * 700) + 25325)).toLocaleString()));
    localStorage.setItem('scotia31', ('$' + (Math.floor((Math.random() * 700) + 26025)).toLocaleString()));
    localStorage.setItem('scotia32', ('$' + (Math.floor((Math.random() * 700) + 26725)).toLocaleString()));
    localStorage.setItem('scotia33', ('$' + (Math.floor((Math.random() * 700) + 27425)).toLocaleString()));
    localStorage.setItem('scotia34', ('$' + (Math.floor((Math.random() * 700) + 28125)).toLocaleString()));
    localStorage.setItem('scotia35', ('$' + (Math.floor((Math.random() * 700) + 28825)).toLocaleString()));
    localStorage.setItem('scotia36', ('$' + (Math.floor((Math.random() * 700) + 29525)).toLocaleString()));
    localStorage.setItem('scotia37', ('$' + (Math.floor((Math.random() * 700) + 30225)).toLocaleString()));

    

    document.getElementById("scotia1").innerHTML = localStorage.getItem('scotia1');
    document.getElementById("scotia2").innerHTML = localStorage.getItem('scotia2');
    document.getElementById("scotia3").innerHTML = localStorage.getItem('scotia3');
    document.getElementById("scotia4").innerHTML = localStorage.getItem('scotia4');
    document.getElementById("scotia5").innerHTML = localStorage.getItem('scotia5');
    document.getElementById("scotia6").innerHTML = localStorage.getItem('scotia6');
    document.getElementById("scotia7").innerHTML = localStorage.getItem('scotia7');
    document.getElementById("scotia8").innerHTML = localStorage.getItem('scotia8');
    document.getElementById("scotia9").innerHTML = localStorage.getItem('scotia9');
    document.getElementById("scotia10").innerHTML = localStorage.getItem('scotia10');

    document.getElementById("scotia11").innerHTML = localStorage.getItem('scotia11');
    document.getElementById("scotia12").innerHTML = localStorage.getItem('scotia12');
    document.getElementById("scotia13").innerHTML = localStorage.getItem('scotia13');
    document.getElementById("scotia14").innerHTML = localStorage.getItem('scotia14');
    document.getElementById("scotia15").innerHTML = localStorage.getItem('scotia15');
    document.getElementById("scotia16").innerHTML = localStorage.getItem('scotia16');
    document.getElementById("scotia17").innerHTML = localStorage.getItem('scotia17');
    document.getElementById("scotia18").innerHTML = localStorage.getItem('scotia18');
    document.getElementById("scotia19").innerHTML = localStorage.getItem('scotia19');
    document.getElementById("scotia20").innerHTML = localStorage.getItem('scotia20');
    document.getElementById("scotia21").innerHTML = localStorage.getItem('scotia21');
    document.getElementById("scotia22").innerHTML = localStorage.getItem('scotia22');
    document.getElementById("scotia23").innerHTML = localStorage.getItem('scotia23');
    document.getElementById("scotia24").innerHTML = localStorage.getItem('scotia24');
    document.getElementById("scotia25").innerHTML = localStorage.getItem('scotia25');
    document.getElementById("scotia26").innerHTML = localStorage.getItem('scotia26');
    document.getElementById("scotia27").innerHTML = localStorage.getItem('scotia27');
    document.getElementById("scotia28").innerHTML = localStorage.getItem('scotia28');
    document.getElementById("scotia29").innerHTML = localStorage.getItem('scotia29');
    document.getElementById("scotia30").innerHTML = localStorage.getItem('scotia30');
    document.getElementById("scotia31").innerHTML = localStorage.getItem('scotia31');
    document.getElementById("scotia32").innerHTML = localStorage.getItem('scotia32');
    document.getElementById("scotia33").innerHTML = localStorage.getItem('scotia33');
    document.getElementById("scotia34").innerHTML = localStorage.getItem('scotia34');
    document.getElementById("scotia35").innerHTML = localStorage.getItem('scotia35');
    document.getElementById("scotia36").innerHTML = localStorage.getItem('scotia36');
    document.getElementById("scotia37").innerHTML = localStorage.getItem('scotia37');



    document.getElementById("scotia01").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('scotia1').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("scotia02").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('scotia2').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("scotia03").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('scotia3').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("scotia04").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('scotia4').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("scotia05").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('scotia5').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("scotia06").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('scotia6').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("scotia07").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('scotia7').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("scotia08").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('scotia8').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("scotia09").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('scotia9').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("scotia010").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('scotia10').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();

    document.getElementById("scotia011").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('scotia11').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("scotia012").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('scotia12').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("scotia013").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('scotia13').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("scotia014").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('scotia14').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("scotia015").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('scotia15').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("scotia016").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('scotia16').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("scotia017").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('scotia17').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("scotia018").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('scotia18').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("scotia019").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('scotia19').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("scotia020").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('scotia20').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("scotia021").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('scotia21').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("scotia022").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('scotia22').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("scotia023").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('scotia23').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("scotia024").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('scotia24').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("scotia025").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('scotia25').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("scotia026").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('scotia26').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("scotia027").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('scotia27').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("scotia028").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('scotia28').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("scotia029").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('scotia29').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("scotia030").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('scotia30').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("scotia031").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('scotia31').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("scotia032").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('scotia32').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("scotia033").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('scotia33').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("scotia034").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('scotia34').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("scotia035").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('scotia35').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("scotia036").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('scotia36').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("scotia037").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('scotia37').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();

} else{
    document.getElementById("scotia1").innerHTML = localStorage.getItem('scotia1');
    document.getElementById("scotia2").innerHTML = localStorage.getItem('scotia2');
    document.getElementById("scotia3").innerHTML = localStorage.getItem('scotia3');
    document.getElementById("scotia4").innerHTML = localStorage.getItem('scotia4');
    document.getElementById("scotia5").innerHTML = localStorage.getItem('scotia5');
    document.getElementById("scotia6").innerHTML = localStorage.getItem('scotia6');
    document.getElementById("scotia7").innerHTML = localStorage.getItem('scotia7');
    document.getElementById("scotia8").innerHTML = localStorage.getItem('scotia8');
    document.getElementById("scotia9").innerHTML = localStorage.getItem('scotia9');
    document.getElementById("scotia10").innerHTML = localStorage.getItem('scotia10');

    document.getElementById("scotia11").innerHTML = localStorage.getItem('scotia11');
    document.getElementById("scotia12").innerHTML = localStorage.getItem('scotia12');
    document.getElementById("scotia13").innerHTML = localStorage.getItem('scotia13');
    document.getElementById("scotia14").innerHTML = localStorage.getItem('scotia14');
    document.getElementById("scotia15").innerHTML = localStorage.getItem('scotia15');
    document.getElementById("scotia16").innerHTML = localStorage.getItem('scotia16');
    document.getElementById("scotia17").innerHTML = localStorage.getItem('scotia17');
    document.getElementById("scotia18").innerHTML = localStorage.getItem('scotia18');
    document.getElementById("scotia19").innerHTML = localStorage.getItem('scotia19');
    document.getElementById("scotia20").innerHTML = localStorage.getItem('scotia20');
    document.getElementById("scotia21").innerHTML = localStorage.getItem('scotia21');
    document.getElementById("scotia22").innerHTML = localStorage.getItem('scotia22');
    document.getElementById("scotia23").innerHTML = localStorage.getItem('scotia23');
    document.getElementById("scotia24").innerHTML = localStorage.getItem('scotia24');
    document.getElementById("scotia25").innerHTML = localStorage.getItem('scotia25');
    document.getElementById("scotia26").innerHTML = localStorage.getItem('scotia26');
    document.getElementById("scotia27").innerHTML = localStorage.getItem('scotia27');
    document.getElementById("scotia28").innerHTML = localStorage.getItem('scotia28');
    document.getElementById("scotia29").innerHTML = localStorage.getItem('scotia29');
    document.getElementById("scotia30").innerHTML = localStorage.getItem('scotia30');
    document.getElementById("scotia31").innerHTML = localStorage.getItem('scotia31');
    document.getElementById("scotia32").innerHTML = localStorage.getItem('scotia32');
    document.getElementById("scotia33").innerHTML = localStorage.getItem('scotia33');
    document.getElementById("scotia34").innerHTML = localStorage.getItem('scotia34');
    document.getElementById("scotia35").innerHTML = localStorage.getItem('scotia35');
    document.getElementById("scotia36").innerHTML = localStorage.getItem('scotia36');
    document.getElementById("scotia37").innerHTML = localStorage.getItem('scotia37');



    document.getElementById("scotia01").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('scotia1').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("scotia02").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('scotia2').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("scotia03").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('scotia3').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("scotia04").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('scotia4').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("scotia05").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('scotia5').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("scotia06").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('scotia6').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("scotia07").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('scotia7').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("scotia08").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('scotia8').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("scotia09").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('scotia9').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("scotia010").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('scotia10').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();

    document.getElementById("scotia011").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('scotia11').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("scotia012").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('scotia12').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("scotia013").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('scotia13').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("scotia014").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('scotia14').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("scotia015").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('scotia15').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("scotia016").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('scotia16').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("scotia017").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('scotia17').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("scotia018").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('scotia18').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("scotia019").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('scotia19').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("scotia020").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('scotia20').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("scotia021").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('scotia21').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("scotia022").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('scotia22').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("scotia023").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('scotia23').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("scotia024").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('scotia24').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("scotia025").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('scotia25').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("scotia026").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('scotia26').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("scotia027").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('scotia27').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("scotia028").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('scotia28').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("scotia029").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('scotia29').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("scotia030").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('scotia30').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("scotia031").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('scotia31').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("scotia032").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('scotia32').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("scotia033").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('scotia33').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("scotia034").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('scotia34').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("scotia035").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('scotia35').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("scotia036").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('scotia36').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("scotia037").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('scotia37').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();

}

localStorage.setItem('loadedscotia',true);
