if(!localStorage.getItem('loadedsun')){
    localStorage.setItem('sun1', ('$' + (Math.floor((Math.random() * 700) + 10025)).toLocaleString()));
    localStorage.setItem('sun2', ('$' + (Math.floor((Math.random() * 700) + 10725)).toLocaleString()));
    localStorage.setItem('sun3', ('$' + (Math.floor((Math.random() * 700) + 11425)).toLocaleString()));
    localStorage.setItem('sun4', ('$' + (Math.floor((Math.random() * 700) + 12125)).toLocaleString()));
    localStorage.setItem('sun5', ('$' + (Math.floor((Math.random() * 700) + 12825)).toLocaleString()));
    localStorage.setItem('sun6', ('$' + (Math.floor((Math.random() * 700) + 13525)).toLocaleString()));
    localStorage.setItem('sun7', ('$' + (Math.floor((Math.random() * 700) + 14225)).toLocaleString()));
    localStorage.setItem('sun8', ('$' + (Math.floor((Math.random() * 700) + 14925)).toLocaleString()));
    localStorage.setItem('sun9', ('$' + (Math.floor((Math.random() * 700) + 15625)).toLocaleString()));
    localStorage.setItem('sun10', ('$' + (Math.floor((Math.random() * 700) + 16325)).toLocaleString()));
    localStorage.setItem('sun11', ('$' + (Math.floor((Math.random() * 700) + 17025)).toLocaleString()));
    localStorage.setItem('sun12', ('$' + (Math.floor((Math.random() * 700) + 17725)).toLocaleString()));
    localStorage.setItem('sun13', ('$' + (Math.floor((Math.random() * 700) + 18425)).toLocaleString()));
    localStorage.setItem('sun14', ('$' + (Math.floor((Math.random() * 700) + 19125)).toLocaleString()));
    localStorage.setItem('sun15', ('$' + (Math.floor((Math.random() * 700) + 19825)).toLocaleString()));
    localStorage.setItem('sun16', ('$' + (Math.floor((Math.random() * 700) + 20525)).toLocaleString()));
    localStorage.setItem('sun17', ('$' + (Math.floor((Math.random() * 700) + 21225)).toLocaleString()));
    localStorage.setItem('sun18', ('$' + (Math.floor((Math.random() * 700) + 21925)).toLocaleString()));
    localStorage.setItem('sun19', ('$' + (Math.floor((Math.random() * 700) + 22625)).toLocaleString()));
    localStorage.setItem('sun20', ('$' + (Math.floor((Math.random() * 700) + 23325)).toLocaleString()));
    localStorage.setItem('sun21', ('$' + (Math.floor((Math.random() * 700) + 24025)).toLocaleString()));
    localStorage.setItem('sun22', ('$' + (Math.floor((Math.random() * 700) + 24725)).toLocaleString()));
    localStorage.setItem('sun23', ('$' + (Math.floor((Math.random() * 700) + 25425)).toLocaleString()));
    localStorage.setItem('sun24', ('$' + (Math.floor((Math.random() * 700) + 26125)).toLocaleString()));
    localStorage.setItem('sun25', ('$' + (Math.floor((Math.random() * 700) + 27825)).toLocaleString()));
    localStorage.setItem('sun26', ('$' + (Math.floor((Math.random() * 700) + 27525)).toLocaleString()));
    localStorage.setItem('sun27', ('$' + (Math.floor((Math.random() * 700) + 28225)).toLocaleString()));
    localStorage.setItem('sun28', ('$' + (Math.floor((Math.random() * 700) + 28925)).toLocaleString()));
    localStorage.setItem('sun29', ('$' + (Math.floor((Math.random() * 700) + 29625)).toLocaleString()));
    localStorage.setItem('sun30', ('$' + (Math.floor((Math.random() * 700) + 30325)).toLocaleString()));
    localStorage.setItem('sun31', ('$' + (Math.floor((Math.random() * 700) + 31025)).toLocaleString()));
    localStorage.setItem('sun32', ('$' + (Math.floor((Math.random() * 700) + 31725)).toLocaleString()));
    localStorage.setItem('sun33', ('$' + (Math.floor((Math.random() * 700) + 32425)).toLocaleString()));
    localStorage.setItem('sun34', ('$' + (Math.floor((Math.random() * 700) + 33125)).toLocaleString()));
    localStorage.setItem('sun35', ('$' + (Math.floor((Math.random() * 700) + 33825)).toLocaleString()));
    localStorage.setItem('sun36', ('$' + (Math.floor((Math.random() * 700) + 34525)).toLocaleString()));
    localStorage.setItem('sun37', ('$' + (Math.floor((Math.random() * 700) + 35225)).toLocaleString()));
    localStorage.setItem('sun38', ('$' + (Math.floor((Math.random() * 700) + 35925)).toLocaleString()));
    localStorage.setItem('sun39', ('$' + (Math.floor((Math.random() * 700) + 36625)).toLocaleString()));
    localStorage.setItem('sun40', ('$' + (Math.floor((Math.random() * 700) + 37325)).toLocaleString()));
    localStorage.setItem('sun41', ('$' + (Math.floor((Math.random() * 700) + 38025)).toLocaleString()));
    localStorage.setItem('sun42', ('$' + (Math.floor((Math.random() * 700) + 38725)).toLocaleString()));
    localStorage.setItem('sun43', ('$' + (Math.floor((Math.random() * 700) + 39425)).toLocaleString()));
    localStorage.setItem('sun44', ('$' + (Math.floor((Math.random() * 700) + 40125)).toLocaleString()));
    localStorage.setItem('sun45', ('$' + (Math.floor((Math.random() * 700) + 40825)).toLocaleString()));
    localStorage.setItem('sun46', ('$' + (Math.floor((Math.random() * 700) + 41525)).toLocaleString()));
    localStorage.setItem('sun47', ('$' + (Math.floor((Math.random() * 700) + 42225)).toLocaleString()));
    localStorage.setItem('sun48', ('$' + (Math.floor((Math.random() * 700) + 42925)).toLocaleString()));
    localStorage.setItem('sun49', ('$' + (Math.floor((Math.random() * 700) + 43625)).toLocaleString()));
    localStorage.setItem('sun50', ('$' + (Math.floor((Math.random() * 700) + 44325)).toLocaleString()));



    document.getElementById("sun1").innerHTML = localStorage.getItem('sun1');
    document.getElementById("sun2").innerHTML = localStorage.getItem('sun2');
    document.getElementById("sun3").innerHTML = localStorage.getItem('sun3');
    document.getElementById("sun4").innerHTML = localStorage.getItem('sun4');
    document.getElementById("sun5").innerHTML = localStorage.getItem('sun5');
    document.getElementById("sun6").innerHTML = localStorage.getItem('sun6');
    document.getElementById("sun7").innerHTML = localStorage.getItem('sun7');
    document.getElementById("sun8").innerHTML = localStorage.getItem('sun8');
    document.getElementById("sun9").innerHTML = localStorage.getItem('sun9');
    document.getElementById("sun10").innerHTML = localStorage.getItem('sun10');

    document.getElementById("sun11").innerHTML = localStorage.getItem('sun11');
    document.getElementById("sun12").innerHTML = localStorage.getItem('sun12');
    document.getElementById("sun13").innerHTML = localStorage.getItem('sun13');
    document.getElementById("sun14").innerHTML = localStorage.getItem('sun14');
    document.getElementById("sun15").innerHTML = localStorage.getItem('sun15');
    document.getElementById("sun16").innerHTML = localStorage.getItem('sun16');
    document.getElementById("sun17").innerHTML = localStorage.getItem('sun17');
    document.getElementById("sun18").innerHTML = localStorage.getItem('sun18');
    document.getElementById("sun19").innerHTML = localStorage.getItem('sun19');
    document.getElementById("sun20").innerHTML = localStorage.getItem('sun20');
    document.getElementById("sun21").innerHTML = localStorage.getItem('sun21');
    document.getElementById("sun22").innerHTML = localStorage.getItem('sun22');
    document.getElementById("sun23").innerHTML = localStorage.getItem('sun23');
    document.getElementById("sun24").innerHTML = localStorage.getItem('sun24');
    document.getElementById("sun25").innerHTML = localStorage.getItem('sun25');
    document.getElementById("sun26").innerHTML = localStorage.getItem('sun26');
    document.getElementById("sun27").innerHTML = localStorage.getItem('sun27');
    document.getElementById("sun28").innerHTML = localStorage.getItem('sun28');
    document.getElementById("sun29").innerHTML = localStorage.getItem('sun29');
    document.getElementById("sun30").innerHTML = localStorage.getItem('sun30');
    document.getElementById("sun31").innerHTML = localStorage.getItem('sun31');
    document.getElementById("sun32").innerHTML = localStorage.getItem('sun32');
    document.getElementById("sun33").innerHTML = localStorage.getItem('sun33');
    document.getElementById("sun34").innerHTML = localStorage.getItem('sun34');
    document.getElementById("sun35").innerHTML = localStorage.getItem('sun35');
    document.getElementById("sun36").innerHTML = localStorage.getItem('sun36');
    document.getElementById("sun37").innerHTML = localStorage.getItem('sun37');
    document.getElementById("sun38").innerHTML = localStorage.getItem('sun38');
    document.getElementById("sun39").innerHTML = localStorage.getItem('sun39');
    document.getElementById("sun40").innerHTML = localStorage.getItem('sun40');
    document.getElementById("sun41").innerHTML = localStorage.getItem('sun41');
    document.getElementById("sun42").innerHTML = localStorage.getItem('sun42');
    document.getElementById("sun43").innerHTML = localStorage.getItem('sun43');
    document.getElementById("sun44").innerHTML = localStorage.getItem('sun44');
    document.getElementById("sun45").innerHTML = localStorage.getItem('sun45');
    document.getElementById("sun46").innerHTML = localStorage.getItem('sun46');
    document.getElementById("sun47").innerHTML = localStorage.getItem('sun47');
    document.getElementById("sun48").innerHTML = localStorage.getItem('sun48');
    document.getElementById("sun49").innerHTML = localStorage.getItem('sun49');
    document.getElementById("sun50").innerHTML = localStorage.getItem('sun50');



    document.getElementById("sun01").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('sun1').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("sun02").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('sun2').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("sun03").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('sun3').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("sun04").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('sun4').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("sun05").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('sun5').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("sun06").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('sun6').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("sun07").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('sun7').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("sun08").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('sun8').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("sun09").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('sun9').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("sun010").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('sun10').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();

    document.getElementById("sun011").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('sun11').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("sun012").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('sun12').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("sun013").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('sun13').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("sun014").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('sun14').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("sun015").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('sun15').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("sun016").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('sun16').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("sun017").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('sun17').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("sun018").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('sun18').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("sun019").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('sun19').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("sun020").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('sun20').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("sun021").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('sun21').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("sun022").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('sun22').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("sun023").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('sun23').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("sun024").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('sun24').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("sun025").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('sun25').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("sun026").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('sun26').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("sun027").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('sun27').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("sun028").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('sun28').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("sun029").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('sun29').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("sun030").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('sun30').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("sun031").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('sun31').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("sun032").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('sun32').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("sun033").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('sun33').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("sun034").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('sun34').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("sun035").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('sun35').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("sun036").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('sun36').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("sun037").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('sun37').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("sun038").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('sun38').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("sun039").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('sun39').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("sun040").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('sun40').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("sun041").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('sun41').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("sun042").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('sun42').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("sun043").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('sun43').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("sun044").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('sun44').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("sun045").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('sun45').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("sun046").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('sun46').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("sun047").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('sun47').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("sun048").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('sun48').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("sun049").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('sun49').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("sun050").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('sun50').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();

} else{
    document.getElementById("sun1").innerHTML = localStorage.getItem('sun1');
    document.getElementById("sun2").innerHTML = localStorage.getItem('sun2');
    document.getElementById("sun3").innerHTML = localStorage.getItem('sun3');
    document.getElementById("sun4").innerHTML = localStorage.getItem('sun4');
    document.getElementById("sun5").innerHTML = localStorage.getItem('sun5');
    document.getElementById("sun6").innerHTML = localStorage.getItem('sun6');
    document.getElementById("sun7").innerHTML = localStorage.getItem('sun7');
    document.getElementById("sun8").innerHTML = localStorage.getItem('sun8');
    document.getElementById("sun9").innerHTML = localStorage.getItem('sun9');
    document.getElementById("sun10").innerHTML = localStorage.getItem('sun10');

    document.getElementById("sun11").innerHTML = localStorage.getItem('sun11');
    document.getElementById("sun12").innerHTML = localStorage.getItem('sun12');
    document.getElementById("sun13").innerHTML = localStorage.getItem('sun13');
    document.getElementById("sun14").innerHTML = localStorage.getItem('sun14');
    document.getElementById("sun15").innerHTML = localStorage.getItem('sun15');
    document.getElementById("sun16").innerHTML = localStorage.getItem('sun16');
    document.getElementById("sun17").innerHTML = localStorage.getItem('sun17');
    document.getElementById("sun18").innerHTML = localStorage.getItem('sun18');
    document.getElementById("sun19").innerHTML = localStorage.getItem('sun19');
    document.getElementById("sun20").innerHTML = localStorage.getItem('sun20');
    document.getElementById("sun21").innerHTML = localStorage.getItem('sun21');
    document.getElementById("sun22").innerHTML = localStorage.getItem('sun22');
    document.getElementById("sun23").innerHTML = localStorage.getItem('sun23');
    document.getElementById("sun24").innerHTML = localStorage.getItem('sun24');
    document.getElementById("sun25").innerHTML = localStorage.getItem('sun25');
    document.getElementById("sun26").innerHTML = localStorage.getItem('sun26');
    document.getElementById("sun27").innerHTML = localStorage.getItem('sun27');
    document.getElementById("sun28").innerHTML = localStorage.getItem('sun28');
    document.getElementById("sun29").innerHTML = localStorage.getItem('sun29');
    document.getElementById("sun30").innerHTML = localStorage.getItem('sun30');
    document.getElementById("sun31").innerHTML = localStorage.getItem('sun31');
    document.getElementById("sun32").innerHTML = localStorage.getItem('sun32');
    document.getElementById("sun33").innerHTML = localStorage.getItem('sun33');
    document.getElementById("sun34").innerHTML = localStorage.getItem('sun34');
    document.getElementById("sun35").innerHTML = localStorage.getItem('sun35');
    document.getElementById("sun36").innerHTML = localStorage.getItem('sun36');
    document.getElementById("sun37").innerHTML = localStorage.getItem('sun37');
    document.getElementById("sun38").innerHTML = localStorage.getItem('sun38');
    document.getElementById("sun39").innerHTML = localStorage.getItem('sun39');
    document.getElementById("sun40").innerHTML = localStorage.getItem('sun40');
    document.getElementById("sun41").innerHTML = localStorage.getItem('sun41');
    document.getElementById("sun42").innerHTML = localStorage.getItem('sun42');
    document.getElementById("sun43").innerHTML = localStorage.getItem('sun43');
    document.getElementById("sun44").innerHTML = localStorage.getItem('sun44');
    document.getElementById("sun45").innerHTML = localStorage.getItem('sun45');
    document.getElementById("sun46").innerHTML = localStorage.getItem('sun46');
    document.getElementById("sun47").innerHTML = localStorage.getItem('sun47');
    document.getElementById("sun48").innerHTML = localStorage.getItem('sun48');
    document.getElementById("sun49").innerHTML = localStorage.getItem('sun49');
    document.getElementById("sun50").innerHTML = localStorage.getItem('sun50');



    document.getElementById("sun01").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('sun1').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("sun02").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('sun2').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("sun03").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('sun3').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("sun04").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('sun4').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("sun05").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('sun5').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("sun06").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('sun6').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("sun07").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('sun7').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("sun08").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('sun8').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("sun09").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('sun9').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("sun010").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('sun10').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();

    document.getElementById("sun011").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('sun11').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("sun012").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('sun12').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("sun013").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('sun13').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("sun014").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('sun14').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("sun015").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('sun15').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("sun016").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('sun16').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("sun017").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('sun17').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("sun018").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('sun18').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("sun019").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('sun19').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("sun020").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('sun20').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("sun021").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('sun21').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("sun022").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('sun22').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("sun023").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('sun23').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("sun024").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('sun24').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("sun025").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('sun25').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("sun026").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('sun26').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("sun027").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('sun27').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("sun028").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('sun28').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("sun029").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('sun29').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("sun030").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('sun30').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("sun031").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('sun31').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("sun032").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('sun32').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("sun033").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('sun33').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("sun034").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('sun34').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("sun035").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('sun35').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("sun036").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('sun36').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("sun037").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('sun37').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("sun038").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('sun38').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("sun039").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('sun39').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("sun040").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('sun40').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("sun041").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('sun41').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("sun042").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('sun42').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("sun043").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('sun43').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("sun044").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('sun44').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("sun045").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('sun45').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("sun046").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('sun46').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("sun047").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('sun47').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("sun048").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('sun48').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("sun049").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('sun49').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();
    document.getElementById("sun050").innerHTML = 'Buy: $' + parseFloat((localStorage.getItem('sun50').replace('$','').replace(',','')/50).toFixed(0)).toLocaleString();

}

localStorage.setItem('loadedsun',true);
